/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Accuracy_H_
#define	_Accuracy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Accuracy */
typedef struct Accuracy {
	long	*seconds	/* OPTIONAL */;
	long	*millis	/* OPTIONAL */;
	long	*micros	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Accuracy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Accuracy;

#ifdef __cplusplus
}
#endif

#endif	/* _Accuracy_H_ */
