/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AllOrFirstTier_H_
#define	_AllOrFirstTier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AllOrFirstTier {
	AllOrFirstTier_allReceipts	= 0,
	AllOrFirstTier_firstTierRecipients	= 1
} e_AllOrFirstTier;

/* AllOrFirstTier */
typedef long	 AllOrFirstTier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AllOrFirstTier;
asn_struct_free_f AllOrFirstTier_free;
asn_struct_print_f AllOrFirstTier_print;
asn_constr_check_f AllOrFirstTier_constraint;
ber_type_decoder_f AllOrFirstTier_decode_ber;
der_type_encoder_f AllOrFirstTier_encode_der;
xer_type_decoder_f AllOrFirstTier_decode_xer;
xer_type_encoder_f AllOrFirstTier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AllOrFirstTier_H_ */
