/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ArchiveTimeStampToken_H_
#define	_ArchiveTimeStampToken_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeStampToken.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ArchiveTimeStampToken */
typedef TimeStampToken_t	 ArchiveTimeStampToken_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArchiveTimeStampToken;
asn_struct_free_f ArchiveTimeStampToken_free;
asn_struct_print_f ArchiveTimeStampToken_print;
asn_constr_check_f ArchiveTimeStampToken_constraint;
ber_type_decoder_f ArchiveTimeStampToken_decode_ber;
der_type_encoder_f ArchiveTimeStampToken_encode_der;
xer_type_decoder_f ArchiveTimeStampToken_decode_xer;
xer_type_encoder_f ArchiveTimeStampToken_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ArchiveTimeStampToken_H_ */
