/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "AttributeCertificateVersion1"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AttCertVersionV1_H_
#define	_AttCertVersionV1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AttCertVersionV1 {
	AttCertVersionV1_v1	= 0
} e_AttCertVersionV1;

/* AttCertVersionV1 */
typedef long	 AttCertVersionV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttCertVersionV1;
asn_struct_free_f AttCertVersionV1_free;
asn_struct_print_f AttCertVersionV1_print;
asn_constr_check_f AttCertVersionV1_constraint;
ber_type_decoder_f AttCertVersionV1_decode_ber;
der_type_encoder_f AttCertVersionV1_encode_der;
xer_type_decoder_f AttCertVersionV1_decode_xer;
xer_type_encoder_f AttCertVersionV1_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AttCertVersionV1_H_ */
