/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AttributeConstraints_H_
#define	_AttributeConstraints_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AttributeTypeConstraints;
struct AttributeValueConstraints;

/* AttributeConstraints */
typedef struct AttributeConstraints {
	struct AttributeTypeConstraints	*attributeTypeConstraints	/* OPTIONAL */;
	struct AttributeValueConstraints	*attributeValueConstraints	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeConstraints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeConstraints;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AttributeTypeConstraints.h"
#include "AttributeValueConstraints.h"

#endif	/* _AttributeConstraints_H_ */
