/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AttributeTypeConstraints_H_
#define	_AttributeTypeConstraints_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeTypeConstraints */
typedef struct AttributeTypeConstraints {
	A_SEQUENCE_OF(AttributeType_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeTypeConstraints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeTypeConstraints;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeTypeConstraints_H_ */
