/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_AttributeTrustCondition_H_
#define	_AttributeTrustCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "HowCertAttribute.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateTrustTrees;
struct CertRevReq;
struct AttributeConstraints;

/* AttributeTrustCondition */
typedef struct AttributeTrustCondition {
	BOOLEAN_t	 attributeMandated;
	HowCertAttribute_t	 howCertAttribute;
	struct CertificateTrustTrees	*attrCertificateTrustTrees	/* OPTIONAL */;
	struct CertRevReq	*attrRevReq	/* OPTIONAL */;
	struct AttributeConstraints	*attributeConstraints	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeTrustCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeTrustCondition;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateTrustTrees.h"
#include "CertRevReq.h"
#include "AttributeConstraints.h"

#endif	/* _AttributeTrustCondition_H_ */
