/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Authenticator_H_
#define	_Authenticator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Authenticator */
typedef UTF8String_t	 Authenticator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authenticator;
asn_struct_free_f Authenticator_free;
asn_struct_print_f Authenticator_print;
asn_constr_check_f Authenticator_constraint;
ber_type_decoder_f Authenticator_decode_ber;
der_type_encoder_f Authenticator_encode_der;
xer_type_decoder_f Authenticator_decode_xer;
xer_type_encoder_f Authenticator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Authenticator_H_ */
