/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CAKeyUpdAnnContent_H_
#define	_CAKeyUpdAnnContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Certificate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CAKeyUpdAnnContent */
typedef struct CAKeyUpdAnnContent {
	Certificate_t	 oldWithNew;
	Certificate_t	 newWithOld;
	Certificate_t	 newWithNew;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAKeyUpdAnnContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAKeyUpdAnnContent;

#ifdef __cplusplus
}
#endif

#endif	/* _CAKeyUpdAnnContent_H_ */
