/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertRepMessage_H_
#define	_CertRepMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Certificate;
struct CertResponse;

/* CertRepMessage */
typedef struct CertRepMessage {
	struct caPubs {
		A_SEQUENCE_OF(struct Certificate) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *caPubs;
	struct response {
		A_SEQUENCE_OF(struct CertResponse) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} response;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertRepMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertRepMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Certificate.h"
#include "CertResponse.h"

#endif	/* _CertRepMessage_H_ */
