/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertificateTrustPoint_H_
#define	_CertificateTrustPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Certificate.h"
#include "PathLenConstraint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AcceptablePolicySet;
struct NameConstraints;
struct PolicyConstraints;

/* CertificateTrustPoint */
typedef struct CertificateTrustPoint {
	Certificate_t	 trustpoint;
	PathLenConstraint_t	*pathLenConstraint	/* OPTIONAL */;
	struct AcceptablePolicySet	*acceptablePolicySet	/* OPTIONAL */;
	struct NameConstraints	*nameConstraints	/* OPTIONAL */;
	struct PolicyConstraints	*policyConstraints	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateTrustPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateTrustPoint;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AcceptablePolicySet.h"
#include "NameConstraints.h"
#include "PolicyConstraints.h"

#endif	/* _CertificateTrustPoint_H_ */
