/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertReq_H_
#define	_CertReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertReq */
typedef CertRequest_t	 CertReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertReq;
asn_struct_free_f CertReq_free;
asn_struct_print_f CertReq_print;
asn_constr_check_f CertReq_constraint;
ber_type_decoder_f CertReq_decode_ber;
der_type_encoder_f CertReq_encode_der;
xer_type_decoder_f CertReq_decode_xer;
xer_type_encoder_f CertReq_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CertReq_H_ */
