/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertResponse_H_
#define	_CertResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "PKIStatusInfo.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertifiedKeyPair;

/* CertResponse */
typedef struct CertResponse {
	long	 certReqId;
	PKIStatusInfo_t	 status;
	struct CertifiedKeyPair	*certifiedKeyPair	/* OPTIONAL */;
	OCTET_STRING_t	*rspInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertifiedKeyPair.h"

#endif	/* _CertResponse_H_ */
