/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertOrEncCert_H_
#define	_CertOrEncCert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Certificate.h"
#include "EncryptedValue.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CertOrEncCert_PR {
	CertOrEncCert_PR_NOTHING,	/* No components present */
	CertOrEncCert_PR_certificate,
	CertOrEncCert_PR_encryptedCert
} CertOrEncCert_PR;

/* CertOrEncCert */
typedef struct CertOrEncCert {
	CertOrEncCert_PR present;
	union CertOrEncCert_u {
		Certificate_t	 certificate;
		EncryptedValue_t	 encryptedCert;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertOrEncCert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertOrEncCert;

#ifdef __cplusplus
}
#endif

#endif	/* _CertOrEncCert_H_ */
