/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertificationRequest_H_
#define	_CertificationRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertificationRequestInfo.h"
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificationRequest */
typedef struct CertificationRequest {
	CertificationRequestInfo_t	 certificationRequestInfo;
	AlgorithmIdentifier_t	 signatureAlgorithm;
	BIT_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificationRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificationRequest_H_ */
