/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertInfoReq_H_
#define	_CertInfoReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CertInfoReq {
	CertInfoReq_none	= 0,
	CertInfoReq_signerOnly	= 1,
	CertInfoReq_fullPath	= 2
} e_CertInfoReq;

/* CertInfoReq */
typedef long	 CertInfoReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertInfoReq;
asn_struct_free_f CertInfoReq_free;
asn_struct_print_f CertInfoReq_print;
asn_constr_check_f CertInfoReq_constraint;
ber_type_decoder_f CertInfoReq_decode_ber;
der_type_encoder_f CertInfoReq_encode_der;
xer_type_decoder_f CertInfoReq_decode_xer;
xer_type_encoder_f CertInfoReq_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CertInfoReq_H_ */
