/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertID_H_
#define	_CertID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include <OCTET_STRING.h>
#include "CertificateSerialNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertID */
typedef struct CertID {
	AlgorithmIdentifier_t	 hashAlgorithm;
	OCTET_STRING_t	 issuerNameHash;
	OCTET_STRING_t	 issuerKeyHash;
	CertificateSerialNumber_t	 serialNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertID;

#ifdef __cplusplus
}
#endif

#endif	/* _CertID_H_ */
