/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertificationRequestInfo_H_
#define	_CertificationRequestInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Name.h"
#include "SubjectPublicKeyInfo.h"
#include "Attributes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum version {
	version_v1	= 0
} e_version;

/* CertificationRequestInfo */
typedef struct CertificationRequestInfo {
	long	 version;
	Name_t	 subject;
	SubjectPublicKeyInfo_t	 subjectPKInfo;
	Attributes_t	 attributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificationRequestInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificationRequestInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificationRequestInfo_H_ */
