/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertRequest_H_
#define	_CertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "CertTemplate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Controls;

/* CertRequest */
typedef struct CertRequest {
	long	 certReqId;
	CertTemplate_t	 certTemplate;
	struct Controls	*controls	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Controls.h"

#endif	/* _CertRequest_H_ */
