/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertReqMsg_H_
#define	_CertReqMsg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertRequest.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProofOfPossession;
struct AttributeTypeAndValue;

/* CertReqMsg */
typedef struct CertReqMsg {
	CertRequest_t	 certReq;
	struct ProofOfPossession	*pop	/* OPTIONAL */;
	struct regInfo {
		A_SEQUENCE_OF(struct AttributeTypeAndValue) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertReqMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertReqMsg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProofOfPossession.h"
#include "AttributeTypeAndValue.h"

#endif	/* _CertReqMsg_H_ */
