/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertTemplate_H_
#define	_CertTemplate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Version.h"
#include <NativeInteger.h>
#include "UniqueIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;
struct Name;
struct OptionalValidity;
struct SubjectPublicKeyInfo;
struct Extensions;

/* CertTemplate */
typedef struct CertTemplate {
	Version_t	*version	/* OPTIONAL */;
	long	*serialNumber	/* OPTIONAL */;
	struct AlgorithmIdentifier	*signingAlg	/* OPTIONAL */;
	struct Name	*issuer	/* OPTIONAL */;
	struct OptionalValidity	*validity	/* OPTIONAL */;
	struct Name	*subject	/* OPTIONAL */;
	struct SubjectPublicKeyInfo	*publicKey	/* OPTIONAL */;
	UniqueIdentifier_t	*issuerUID	/* OPTIONAL */;
	UniqueIdentifier_t	*subjectUID	/* OPTIONAL */;
	struct Extensions	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertTemplate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertTemplate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"
#include "Name.h"
#include "OptionalValidity.h"
#include "SubjectPublicKeyInfo.h"
#include "Extensions.h"

#endif	/* _CertTemplate_H_ */
