/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertifiedAttributes_H_
#define	_CertifiedAttributes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeCertificate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertifiedAttributes */
typedef AttributeCertificate_t	 CertifiedAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertifiedAttributes;
asn_struct_free_f CertifiedAttributes_free;
asn_struct_print_f CertifiedAttributes_print;
asn_constr_check_f CertifiedAttributes_constraint;
ber_type_decoder_f CertifiedAttributes_decode_ber;
der_type_encoder_f CertifiedAttributes_encode_der;
xer_type_decoder_f CertifiedAttributes_decode_xer;
xer_type_encoder_f CertifiedAttributes_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CertifiedAttributes_H_ */
