/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Challenge_H_
#define	_Challenge_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;

/* Challenge */
typedef struct Challenge {
	struct AlgorithmIdentifier	*owf	/* OPTIONAL */;
	OCTET_STRING_t	 witness;
	OCTET_STRING_t	 challenge;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Challenge_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Challenge;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"

#endif	/* _Challenge_H_ */
