/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CMSAttributeValue_H_
#define	_CMSAttributeValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ANY.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CMSAttributeValue */
typedef ANY_t	 CMSAttributeValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMSAttributeValue;
asn_struct_free_f CMSAttributeValue_free;
asn_struct_print_f CMSAttributeValue_print;
asn_constr_check_f CMSAttributeValue_constraint;
ber_type_decoder_f CMSAttributeValue_decode_ber;
der_type_encoder_f CMSAttributeValue_encode_der;
xer_type_decoder_f CMSAttributeValue_decode_xer;
xer_type_encoder_f CMSAttributeValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CMSAttributeValue_H_ */
