/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CMSTime_H_
#define	_CMSTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTCTime.h>
#include <GeneralizedTime.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CMSTime_PR {
	CMSTime_PR_NOTHING,	/* No components present */
	CMSTime_PR_utcTime,
	CMSTime_PR_generalTime
} CMSTime_PR;

/* CMSTime */
typedef struct CMSTime {
	CMSTime_PR present;
	union CMSTime_u {
		UTCTime_t	 utcTime;
		GeneralizedTime_t	 generalTime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMSTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMSTime;

#ifdef __cplusplus
}
#endif

#endif	/* _CMSTime_H_ */
