/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CommitmentRule_H_
#define	_CommitmentRule_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SelectedCommitmentTypes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignerAndVerifierRules;
struct SigningCertTrustCondition;
struct TimestampTrustCondition;
struct AttributeTrustCondition;
struct AlgorithmConstraintSet;
struct SignPolExtensions;

/* CommitmentRule */
typedef struct CommitmentRule {
	SelectedCommitmentTypes_t	 selCommitmentTypes;
	struct SignerAndVerifierRules	*signerAndVeriferRules	/* OPTIONAL */;
	struct SigningCertTrustCondition	*signingCertTrustCondition	/* OPTIONAL */;
	struct TimestampTrustCondition	*timeStampTrustCondition	/* OPTIONAL */;
	struct AttributeTrustCondition	*attributeTrustCondition	/* OPTIONAL */;
	struct AlgorithmConstraintSet	*algorithmConstraintSet	/* OPTIONAL */;
	struct SignPolExtensions	*signPolExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommitmentRule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommitmentRule;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignerAndVerifierRules.h"
#include "SigningCertTrustCondition.h"
#include "TimestampTrustCondition.h"
#include "AttributeTrustCondition.h"
#include "AlgorithmConstraintSet.h"
#include "SignPolExtensions.h"

#endif	/* _CommitmentRule_H_ */
