/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CommitmentRules_H_
#define	_CommitmentRules_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CommitmentRule;

/* CommitmentRules */
typedef struct CommitmentRules {
	A_SEQUENCE_OF(struct CommitmentRule) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommitmentRules_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommitmentRules;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CommitmentRule.h"

#endif	/* _CommitmentRules_H_ */
