/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CommitmentType_H_
#define	_CommitmentType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CommitmentTypeIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DirectoryString;

/* CommitmentType */
typedef struct CommitmentType {
	CommitmentTypeIdentifier_t	 identifier;
	struct DirectoryString	*fieldOfApplication	/* OPTIONAL */;
	struct DirectoryString	*semantics	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommitmentType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommitmentType;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FieldOfApplication.h"
#include "DirectoryString.h"

#endif	/* _CommitmentType_H_ */
