/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CommitmentTypeQualifier_H_
#define	_CommitmentTypeQualifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CommitmentTypeIdentifier.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CommitmentTypeQualifier */
typedef struct CommitmentTypeQualifier {
	CommitmentTypeIdentifier_t	 commitmentTypeIdentifier;
	ANY_t	 qualifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommitmentTypeQualifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommitmentTypeQualifier;

#ifdef __cplusplus
}
#endif

#endif	/* _CommitmentTypeQualifier_H_ */
