/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CrlIdentifier_H_
#define	_CrlIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Name.h"
#include <UTCTime.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CrlIdentifier */
typedef struct CrlIdentifier {
	Name_t	 crlissuer;
	UTCTime_t	 crlIssuedTime;
	long	*crlNumber	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CrlIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlIdentifier_H_ */
