/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CrlOcspRef_H_
#define	_CrlOcspRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CRLListID;
struct OcspListID;
struct OtherRevRefs;

/* CrlOcspRef */
typedef struct CrlOcspRef {
	struct CRLListID	*crlids	/* OPTIONAL */;
	struct OcspListID	*ocspids	/* OPTIONAL */;
	struct OtherRevRefs	*otherRev	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CrlOcspRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlOcspRef;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CRLListID.h"
#include "OcspListID.h"
#include "OtherRevRefs.h"

#endif	/* _CrlOcspRef_H_ */
