/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CRMF_EncryptedKey_H_
#define	_CRMF_EncryptedKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EncryptedValue.h"
#include "EnvelopedData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CRMF_EncryptedKey_PR {
	CRMF_EncryptedKey_PR_NOTHING,	/* No components present */
	CRMF_EncryptedKey_PR_encryptedValue,
	CRMF_EncryptedKey_PR_envelopedData
} CRMF_EncryptedKey_PR;

/* CRMF-EncryptedKey */
typedef struct CRMF_EncryptedKey {
	CRMF_EncryptedKey_PR present;
	union CRMF_EncryptedKey_u {
		EncryptedValue_t	 encryptedValue;
		EnvelopedData_t	 envelopedData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CRMF_EncryptedKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CRMF_EncryptedKey;

#ifdef __cplusplus
}
#endif

#endif	/* _CRMF_EncryptedKey_H_ */
