/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DeltaTime_H_
#define	_DeltaTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeltaTime */
typedef struct DeltaTime {
	long	 deltaSeconds;
	long	 deltaMinutes;
	long	 deltaHours;
	long	 deltaDays;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeltaTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaTime;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaTime_H_ */
