/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DHBasedMac_H_
#define	_DHBasedMac_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DHBasedMac */
typedef OBJECT_IDENTIFIER_t	 DHBasedMac_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DHBasedMac;
asn_struct_free_f DHBasedMac_free;
asn_struct_print_f DHBasedMac_print;
asn_constr_check_f DHBasedMac_constraint;
ber_type_decoder_f DHBasedMac_decode_ber;
der_type_encoder_f DHBasedMac_encode_der;
xer_type_decoder_f DHBasedMac_decode_xer;
xer_type_encoder_f DHBasedMac_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DHBasedMac_H_ */
