/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DHBMParameter_H_
#define	_DHBMParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DHBMParameter */
typedef struct DHBMParameter {
	AlgorithmIdentifier_t	 owf;
	AlgorithmIdentifier_t	 mac;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DHBMParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DHBMParameter;

#ifdef __cplusplus
}
#endif

#endif	/* _DHBMParameter_H_ */
