/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DssDictionary_H_
#define	_DssDictionary_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VriDictionary;
struct PdfEntry;

/* DssDictionary */
typedef struct DssDictionary {
	struct mandatedEntries {
		A_SEQUENCE_OF(struct PdfEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mandatedEntries;
	struct VriDictionary	*vriDictionary	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DssDictionary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DssDictionary;

/* Decoder */
DssDictionary_t *DecodeDssDictionary(const void *buf, size_t size);

/* Freeing structure */
void DssDictionary_free(DssDictionary_t *dss);

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VriDictionary.h"
#include "PdfEntry.h"

#endif	/* _DssDictionary_H_ */
