/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DssDictionary_H_
#define	_DssDictionary_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PdfEntry.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VriDictionary;

/* DssDictionary */
typedef struct DssDictionary {
	PdfEntry_t	 type;
	struct VriDictionary	*vriDictionary	/* OPTIONAL */;
	BOOLEAN_t	*paArtifacts	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DssDictionary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DssDictionary;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VriDictionary.h"

#endif	/* _DssDictionary_H_ */
