/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_EncryptedValue_H_
#define	_EncryptedValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;

/* EncryptedValue */
typedef struct EncryptedValue {
	struct AlgorithmIdentifier	*intendedAlg	/* OPTIONAL */;
	struct AlgorithmIdentifier	*symmAlg	/* OPTIONAL */;
	BIT_STRING_t	*encSymmKey	/* OPTIONAL */;
	struct AlgorithmIdentifier	*keyAlg	/* OPTIONAL */;
	OCTET_STRING_t	*valueHint	/* OPTIONAL */;
	BIT_STRING_t	 encValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"

#endif	/* _EncryptedValue_H_ */
