/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_EntityIdentifier_H_
#define	_EntityIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IssuerAndSerialNumber.h"
#include "SubjectKeyIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EntityIdentifier_PR {
	EntityIdentifier_PR_NOTHING,	/* No components present */
	EntityIdentifier_PR_issuerAndSerialNumber,
	EntityIdentifier_PR_subjectKeyIdentifier
} EntityIdentifier_PR;

/* EntityIdentifier */
typedef struct EntityIdentifier {
	EntityIdentifier_PR present;
	union EntityIdentifier_u {
		IssuerAndSerialNumber_t	 issuerAndSerialNumber;
		SubjectKeyIdentifier_t	 subjectKeyIdentifier;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntityIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntityIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _EntityIdentifier_H_ */
