/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_EquivalentLabels_H_
#define	_EquivalentLabels_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ESSSecurityLabel;

/* EquivalentLabels */
typedef struct EquivalentLabels {
	A_SEQUENCE_OF(struct ESSSecurityLabel) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EquivalentLabels_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquivalentLabels;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ESSSecurityLabel.h"

#endif	/* _EquivalentLabels_H_ */
