/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ErrorMsgContent_H_
#define	_ErrorMsgContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKIStatusInfo.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKIFreeText;

/* ErrorMsgContent */
typedef struct ErrorMsgContent {
	PKIStatusInfo_t	 pKIStatusInfo;
	long	*errorCode	/* OPTIONAL */;
	struct PKIFreeText	*errorDetails	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ErrorMsgContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ErrorMsgContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PKIFreeText.h"

#endif	/* _ErrorMsgContent_H_ */
