/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ESCTimeStampToken_H_
#define	_ESCTimeStampToken_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeStampToken.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ESCTimeStampToken */
typedef TimeStampToken_t	 ESCTimeStampToken_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESCTimeStampToken;
asn_struct_free_f ESCTimeStampToken_free;
asn_struct_print_f ESCTimeStampToken_print;
asn_constr_check_f ESCTimeStampToken_constraint;
ber_type_decoder_f ESCTimeStampToken_decode_ber;
der_type_encoder_f ESCTimeStampToken_encode_der;
xer_type_decoder_f ESCTimeStampToken_decode_xer;
xer_type_encoder_f ESCTimeStampToken_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ESCTimeStampToken_H_ */
