/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ESSPrivacyMark_H_
#define	_ESSPrivacyMark_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <UTF8String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ESSPrivacyMark_PR {
	ESSPrivacyMark_PR_NOTHING,	/* No components present */
	ESSPrivacyMark_PR_pString,
	ESSPrivacyMark_PR_utf8String
} ESSPrivacyMark_PR;

/* ESSPrivacyMark */
typedef struct ESSPrivacyMark {
	ESSPrivacyMark_PR present;
	union ESSPrivacyMark_u {
		PrintableString_t	 pString;
		UTF8String_t	 utf8String;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ESSPrivacyMark_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESSPrivacyMark;

#ifdef __cplusplus
}
#endif

#endif	/* _ESSPrivacyMark_H_ */
