/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ESSSecurityLabel_H_
#define	_ESSSecurityLabel_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecurityPolicyIdentifier.h"
#include "SecurityClassification.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum ESSSecurityLabel_PR {
	ESSSecurityLabel_PR_security_policy_identifier,	/* Member security_policy_identifier is present */
	ESSSecurityLabel_PR_security_classification,	/* Member security_classification is present */
	ESSSecurityLabel_PR_privacy_mark,	/* Member privacy_mark is present */
	ESSSecurityLabel_PR_security_categories,	/* Member security_categories is present */
} ESSSecurityLabel_PR;

/* Forward declarations */
struct ESSPrivacyMark;
struct SecurityCategories;

/* ESSSecurityLabel */
typedef struct ESSSecurityLabel {
	SecurityPolicyIdentifier_t	 security_policy_identifier;
	SecurityClassification_t	*security_classification	/* OPTIONAL */;
	struct ESSPrivacyMark	*privacy_mark	/* OPTIONAL */;
	struct SecurityCategories	*security_categories	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pESSSecurityLabel, ESSSecurityLabel_PR_x) */
	unsigned int _presence_map
		[((4+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ESSSecurityLabel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESSSecurityLabel;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ESSPrivacyMark.h"
#include "SecurityCategories.h"

#endif	/* _ESSSecurityLabel_H_ */
