/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ESSVersion_H_
#define	_ESSVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ESSVersion {
	ESSVersion_v1	= 1
} e_ESSVersion;

/* ESSVersion */
typedef long	 ESSVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESSVersion;
asn_struct_free_f ESSVersion_free;
asn_struct_print_f ESSVersion_print;
asn_constr_check_f ESSVersion_constraint;
ber_type_decoder_f ESSVersion_decode_ber;
der_type_encoder_f ESSVersion_encode_der;
xer_type_decoder_f ESSVersion_decode_xer;
xer_type_encoder_f ESSVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ESSVersion_H_ */
