/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_GenRepContent_H_
#define	_GenRepContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InfoTypeAndValue;

/* GenRepContent */
typedef struct GenRepContent {
	A_SEQUENCE_OF(struct InfoTypeAndValue) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenRepContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenRepContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InfoTypeAndValue.h"

#endif	/* _GenRepContent_H_ */
