/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_KeyGenParameters_H_
#define	_KeyGenParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KeyGenParameters */
typedef OCTET_STRING_t	 KeyGenParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyGenParameters;
asn_struct_free_f KeyGenParameters_free;
asn_struct_print_f KeyGenParameters_print;
asn_constr_check_f KeyGenParameters_constraint;
ber_type_decoder_f KeyGenParameters_decode_ber;
der_type_encoder_f KeyGenParameters_encode_der;
xer_type_decoder_f KeyGenParameters_decode_xer;
xer_type_encoder_f KeyGenParameters_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyGenParameters_H_ */
