/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_KeyRecRepContent_H_
#define	_KeyRecRepContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKIStatusInfo.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Certificate;
struct CertifiedKeyPair;

/* KeyRecRepContent */
typedef struct KeyRecRepContent {
	PKIStatusInfo_t	 status;
	struct Certificate	*newSigCert	/* OPTIONAL */;
	struct caCerts {
		A_SEQUENCE_OF(struct Certificate) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *caCerts;
	struct keyPairHist {
		A_SEQUENCE_OF(struct CertifiedKeyPair) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *keyPairHist;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KeyRecRepContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyRecRepContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Certificate.h"
#include "CertifiedKeyPair.h"

#endif	/* _KeyRecRepContent_H_ */
