/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ListaDePAsAprovadasV2"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_LpaVersion_H_
#define	_LpaVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LpaVersion {
	LpaVersion_v2	= 0
} e_LpaVersion;

/* LpaVersion */
typedef long	 LpaVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LpaVersion;
asn_struct_free_f LpaVersion_free;
asn_struct_print_f LpaVersion_print;
asn_constr_check_f LpaVersion_constraint;
ber_type_decoder_f LpaVersion_decode_ber;
der_type_encoder_f LpaVersion_encode_der;
xer_type_decoder_f LpaVersion_decode_xer;
xer_type_encoder_f LpaVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LpaVersion_H_ */
