/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_MandatedPdfSigDicEntries_H_
#define	_MandatedPdfSigDicEntries_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PdfEntry;

/* MandatedPdfSigDicEntries */
typedef struct MandatedPdfSigDicEntries {
	A_SEQUENCE_OF(struct PdfEntry) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MandatedPdfSigDicEntries_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MandatedPdfSigDicEntries;

/* Decoder */
MandatedPdfSigDicEntries_t*
DecodeMandatedPdfSigDicEntries(const void *buffer, size_t buf_size);

/* Freeing */
void MandatedPdfSigDicEntries_free(MandatedPdfSigDicEntries_t *mandatedEntries);

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PdfEntry.h"

#endif	/* _MandatedPdfSigDicEntries_H_ */
