/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_MLData_H_
#define	_MLData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityIdentifier.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MLReceiptPolicy;

/* MLData */
typedef struct MLData {
	EntityIdentifier_t	 mailListIdentifier;
	GeneralizedTime_t	 expansionTime;
	struct MLReceiptPolicy	*mlReceiptPolicy	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MLData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MLData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MLReceiptPolicy.h"

#endif	/* _MLData_H_ */
