/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_MLReceiptPolicy_H_
#define	_MLReceiptPolicy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MLReceiptPolicy_PR {
	MLReceiptPolicy_PR_NOTHING,	/* No components present */
	MLReceiptPolicy_PR_none,
	MLReceiptPolicy_PR_insteadOf,
	MLReceiptPolicy_PR_inAdditionTo
} MLReceiptPolicy_PR;

/* Forward declarations */
struct GeneralNames;

/* MLReceiptPolicy */
typedef struct MLReceiptPolicy {
	MLReceiptPolicy_PR present;
	union MLReceiptPolicy_u {
		NULL_t	 none;
		struct insteadOf {
			A_SEQUENCE_OF(struct GeneralNames) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} insteadOf;
		struct inAdditionTo {
			A_SEQUENCE_OF(struct GeneralNames) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} inAdditionTo;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MLReceiptPolicy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MLReceiptPolicy;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralNames.h"

#endif	/* _MLReceiptPolicy_H_ */
