/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OcspIdentifier_H_
#define	_OcspIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResponderID.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OcspIdentifier */
typedef struct OcspIdentifier {
	ResponderID_t	 ocspResponderID;
	GeneralizedTime_t	 producedAt;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OcspIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OcspIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _OcspIdentifier_H_ */
