/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OCSP_Version_H_
#define	_OCSP_Version_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OCSP_Version {
	OCSP_Version_v1	= 0
} e_OCSP_Version;

/* OCSP-Version */
typedef long	 OCSP_Version_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OCSP_Version;
asn_struct_free_f OCSP_Version_free;
asn_struct_print_f OCSP_Version_print;
asn_constr_check_f OCSP_Version_constraint;
ber_type_decoder_f OCSP_Version_decode_ber;
der_type_encoder_f OCSP_Version_encode_der;
xer_type_decoder_f OCSP_Version_decode_xer;
xer_type_encoder_f OCSP_Version_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OCSP_Version_H_ */
