/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OcspListID_H_
#define	_OcspListID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OcspResponsesID;

/* OcspListID */
typedef struct OcspListID {
	struct ocspResponses {
		A_SEQUENCE_OF(struct OcspResponsesID) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ocspResponses;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OcspListID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OcspListID;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OcspResponsesID.h"

#endif	/* _OcspListID_H_ */
