/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OCSPRequest_H_
#define	_OCSPRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TBSRequest.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OCSP_Signature;

/* OCSPRequest */
typedef struct OCSPRequest {
	TBSRequest_t	 tbsRequest;
	struct OCSP_Signature	*optionalSignature	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OCSPRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OCSPRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OCSP-Signature.h"

#endif	/* _OCSPRequest_H_ */
