/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OCSPResponseStatus_H_
#define	_OCSPResponseStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OCSPResponseStatus {
	OCSPResponseStatus_successful	= 0,
	OCSPResponseStatus_malformedRequest	= 1,
	OCSPResponseStatus_internalError	= 2,
	OCSPResponseStatus_tryLater	= 3,
	OCSPResponseStatus_sigRequired	= 5,
	OCSPResponseStatus_unauthorized	= 6
} e_OCSPResponseStatus;

/* OCSPResponseStatus */
typedef long	 OCSPResponseStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OCSPResponseStatus;
asn_struct_free_f OCSPResponseStatus_free;
asn_struct_print_f OCSPResponseStatus_print;
asn_constr_check_f OCSPResponseStatus_constraint;
ber_type_decoder_f OCSPResponseStatus_decode_ber;
der_type_encoder_f OCSPResponseStatus_encode_der;
xer_type_decoder_f OCSPResponseStatus_decode_xer;
xer_type_encoder_f OCSPResponseStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OCSPResponseStatus_H_ */
