/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OcspResponsesID_H_
#define	_OcspResponsesID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OcspIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OtherHash;

/* OcspResponsesID */
typedef struct OcspResponsesID {
	OcspIdentifier_t	 ocspIdentifier;
	struct OtherHash	*ocspRepHash	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OcspResponsesID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OcspResponsesID;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OtherHash.h"

#endif	/* _OcspResponsesID_H_ */
