/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OldCertId_H_
#define	_OldCertId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OldCertId */
typedef CertID_t	 OldCertId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OldCertId;
asn_struct_free_f OldCertId_free;
asn_struct_print_f OldCertId_print;
asn_constr_check_f OldCertId_constraint;
ber_type_decoder_f OldCertId_decode_ber;
der_type_encoder_f OldCertId_encode_der;
xer_type_decoder_f OldCertId_decode_xer;
xer_type_encoder_f OldCertId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OldCertId_H_ */
