/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OtherRevValType_H_
#define	_OtherRevValType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtherRevValType */
typedef OBJECT_IDENTIFIER_t	 OtherRevValType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherRevValType;
asn_struct_free_f OtherRevValType_free;
asn_struct_print_f OtherRevValType_print;
asn_constr_check_f OtherRevValType_constraint;
ber_type_decoder_f OtherRevValType_decode_ber;
der_type_encoder_f OtherRevValType_encode_der;
xer_type_decoder_f OtherRevValType_decode_xer;
xer_type_encoder_f OtherRevValType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherRevValType_H_ */
