/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OtherCertID_H_
#define	_OtherCertID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OtherHash.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IssuerSerial;

/* OtherCertID */
typedef struct OtherCertID {
	OtherHash_t	 otherCertHash;
	struct IssuerSerial	*issuerSerial	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherCertID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherCertID;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IssuerSerial.h"

#endif	/* _OtherCertID_H_ */
