/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OtherRevRefs_H_
#define	_OtherRevRefs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OtherRevRefType.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtherRevRefs */
typedef struct OtherRevRefs {
	OtherRevRefType_t	 otherRevRefType;
	ANY_t	 otherRevRefs;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherRevRefs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherRevRefs;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherRevRefs_H_ */
