/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PBMParameter_H_
#define	_PBMParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "AlgorithmIdentifier.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PBMParameter */
typedef struct PBMParameter {
	OCTET_STRING_t	 salt;
	AlgorithmIdentifier_t	 owf;
	long	 iterationCount;
	AlgorithmIdentifier_t	 mac;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PBMParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PBMParameter;

#ifdef __cplusplus
}
#endif

#endif	/* _PBMParameter_H_ */
