/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PdfEntry_H_
#define	_PdfEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PdfEntry */
typedef struct PdfEntry {
	UTF8String_t	 pdfEntryId;
	OCTET_STRING_t	*pdfEntryValue	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PdfEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PdfEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _PdfEntry_H_ */
