/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIArchiveOptions_H_
#define	_PKIArchiveOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRMF-EncryptedKey.h"
#include "KeyGenParameters.h"
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKIArchiveOptions_PR {
	PKIArchiveOptions_PR_NOTHING,	/* No components present */
	PKIArchiveOptions_PR_encryptedPrivKey,
	PKIArchiveOptions_PR_keyGenParameters,
	PKIArchiveOptions_PR_archiveRemGenPrivKey
} PKIArchiveOptions_PR;

/* PKIArchiveOptions */
typedef struct PKIArchiveOptions {
	PKIArchiveOptions_PR present;
	union PKIArchiveOptions_u {
		CRMF_EncryptedKey_t	 encryptedPrivKey;
		KeyGenParameters_t	 keyGenParameters;
		BOOLEAN_t	 archiveRemGenPrivKey;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIArchiveOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIArchiveOptions;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIArchiveOptions_H_ */
