/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIConfirmContent_H_
#define	_PKIConfirmContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKIConfirmContent */
typedef NULL_t	 PKIConfirmContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIConfirmContent;
asn_struct_free_f PKIConfirmContent_free;
asn_struct_print_f PKIConfirmContent_print;
asn_constr_check_f PKIConfirmContent_constraint;
ber_type_decoder_f PKIConfirmContent_decode_ber;
der_type_encoder_f PKIConfirmContent_encode_der;
xer_type_decoder_f PKIConfirmContent_decode_xer;
xer_type_encoder_f PKIConfirmContent_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIConfirmContent_H_ */
