/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIFreeText_H_
#define	_PKIFreeText_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKIFreeText */
typedef struct PKIFreeText {
	A_SEQUENCE_OF(UTF8String_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIFreeText_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIFreeText;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIFreeText_H_ */
