/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIFailureInfo_H_
#define	_PKIFailureInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKIFailureInfo {
	PKIFailureInfo_badAlg	= 0,
	PKIFailureInfo_badMessageCheck	= 1,
	PKIFailureInfo_badRequest	= 2,
	PKIFailureInfo_badTime	= 3,
	PKIFailureInfo_badCertId	= 4,
	PKIFailureInfo_badDataFormat	= 5,
	PKIFailureInfo_wrongAuthority	= 6,
	PKIFailureInfo_incorrectData	= 7,
	PKIFailureInfo_missingTimeStamp	= 8,
	PKIFailureInfo_badPOP	= 9,
	PKIFailureInfo_timeNotAvailable	= 14,
	PKIFailureInfo_unacceptedPolicy	= 15,
	PKIFailureInfo_unacceptedExtension	= 16,
	PKIFailureInfo_addInfoNotAvailable	= 17,
	PKIFailureInfo_systemFailure	= 25
} e_PKIFailureInfo;

/* PKIFailureInfo */
typedef BIT_STRING_t	 PKIFailureInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIFailureInfo;
asn_struct_free_f PKIFailureInfo_free;
asn_struct_print_f PKIFailureInfo_print;
asn_constr_check_f PKIFailureInfo_constraint;
ber_type_decoder_f PKIFailureInfo_decode_ber;
der_type_encoder_f PKIFailureInfo_encode_der;
xer_type_decoder_f PKIFailureInfo_decode_xer;
xer_type_encoder_f PKIFailureInfo_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIFailureInfo_H_ */
