/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIHeader_H_
#define	_PKIHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "GeneralName.h"
#include <GeneralizedTime.h>
#include "KeyIdentifier.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum pvno {
	pvno_ietf_version2	= 1
} e_pvno;

/* Forward declarations */
struct AlgorithmIdentifier;
struct PKIFreeText;
struct InfoTypeAndValue;

/* PKIHeader */
typedef struct PKIHeader {
	long	 pvno;
	GeneralName_t	 sender;
	GeneralName_t	 recipient;
	GeneralizedTime_t	*messageTime	/* OPTIONAL */;
	struct AlgorithmIdentifier	*protectionAlg	/* OPTIONAL */;
	KeyIdentifier_t	*senderKID	/* OPTIONAL */;
	KeyIdentifier_t	*recipKID	/* OPTIONAL */;
	OCTET_STRING_t	*transactionID	/* OPTIONAL */;
	OCTET_STRING_t	*senderNonce	/* OPTIONAL */;
	OCTET_STRING_t	*recipNonce	/* OPTIONAL */;
	struct PKIFreeText	*freeText	/* OPTIONAL */;
	struct generalInfo {
		A_SEQUENCE_OF(struct InfoTypeAndValue) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *generalInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIHeader;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"
#include "PKIFreeText.h"
#include "InfoTypeAndValue.h"

#endif	/* _PKIHeader_H_ */
