/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIMessage_H_
#define	_PKIMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKIHeader.h"
#include "PKIProtection.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKIBody;
struct Certificate;

/* PKIMessage */
typedef struct PKIMessage {
	PKIHeader_t	 header;
	struct PKIBody	*body;
	PKIProtection_t	*protection	/* OPTIONAL */;
	struct extraCerts {
		A_SEQUENCE_OF(struct Certificate) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *extraCerts;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PKIBody.h"
#include "Certificate.h"

#endif	/* _PKIMessage_H_ */
