/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIPublicationInfo_H_
#define	_PKIPublicationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum action {
	action_dontPublish	= 0,
	action_pleasePublish	= 1
} e_action;

/* Forward declarations */
struct SinglePubInfo;

/* PKIPublicationInfo */
typedef struct PKIPublicationInfo {
	long	 action;
	struct pubInfos {
		A_SEQUENCE_OF(struct SinglePubInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pubInfos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIPublicationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIPublicationInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SinglePubInfo.h"

#endif	/* _PKIPublicationInfo_H_ */
