/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIProtection_H_
#define	_PKIProtection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKIProtection */
typedef BIT_STRING_t	 PKIProtection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIProtection;
asn_struct_free_f PKIProtection_free;
asn_struct_print_f PKIProtection_print;
asn_constr_check_f PKIProtection_constraint;
ber_type_decoder_f PKIProtection_decode_ber;
der_type_encoder_f PKIProtection_encode_der;
xer_type_decoder_f PKIProtection_decode_xer;
xer_type_encoder_f PKIProtection_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIProtection_H_ */
