/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIStatus_H_
#define	_PKIStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKIStatus {
	PKIStatus_accepted	= 0,
	PKIStatus_grantedWithMods	= 1,
	PKIStatus_rejection	= 2,
	PKIStatus_waiting	= 3,
	PKIStatus_revocationWarning	= 4,
	PKIStatus_revocationNotification	= 5,
	PKIStatus_keyUpdateWarning	= 6
} e_PKIStatus;

/* PKIStatus */
typedef long	 PKIStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIStatus;
asn_struct_free_f PKIStatus_free;
asn_struct_print_f PKIStatus_print;
asn_constr_check_f PKIStatus_constraint;
ber_type_decoder_f PKIStatus_decode_ber;
der_type_encoder_f PKIStatus_encode_der;
xer_type_decoder_f PKIStatus_decode_xer;
xer_type_encoder_f PKIStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIStatus_H_ */
