/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PKIStatusInfo_H_
#define	_PKIStatusInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKIStatus.h"
#include "PKIFailureInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKIFreeText;

/* PKIStatusInfo */
typedef struct PKIStatusInfo {
	PKIStatus_t	 status;
	struct PKIFreeText	*statusString	/* OPTIONAL */;
	PKIFailureInfo_t	*failInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIStatusInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIStatusInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PKIFreeText.h"

#endif	/* _PKIStatusInfo_H_ */
