/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PolicyIssuerName_H_
#define	_PolicyIssuerName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeneralNames.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PolicyIssuerName */
typedef GeneralNames_t	 PolicyIssuerName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyIssuerName;
asn_struct_free_f PolicyIssuerName_free;
asn_struct_print_f PolicyIssuerName_print;
asn_constr_check_f PolicyIssuerName_constraint;
ber_type_decoder_f PolicyIssuerName_decode_ber;
der_type_encoder_f PolicyIssuerName_encode_der;
xer_type_decoder_f PolicyIssuerName_decode_xer;
xer_type_encoder_f PolicyIssuerName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyIssuerName_H_ */
