/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ListaDePAsAprovadasV2"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PolicyInfo_H_
#define	_PolicyInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SigningPeriod.h"
#include <GeneralizedTime.h>
#include <OBJECT_IDENTIFIER.h>
#include <IA5String.h>
#include "OtherHashAlgAndValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PolicyInfo */
typedef struct PolicyInfo {
	SigningPeriod_t	 signingPeriod;
	GeneralizedTime_t	*revocationDate	/* OPTIONAL */;
	OBJECT_IDENTIFIER_t	 policyOID;
	IA5String_t	 policyURI;
	OtherHashAlgAndValue_t	 policyDigest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolicyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolicyInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _PolicyInfo_H_ */
