/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_POPOSigningKey_H_
#define	_POPOSigningKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct POPOSigningKeyInput;

/* POPOSigningKey */
typedef struct POPOSigningKey {
	struct POPOSigningKeyInput	*poposkInput	/* OPTIONAL */;
	AlgorithmIdentifier_t	 algorithmIdentifier;
	BIT_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} POPOSigningKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_POPOSigningKey;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "POPOSigningKeyInput.h"

#endif	/* _POPOSigningKey_H_ */
