/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_POPOSigningKeyInput_H_
#define	_POPOSigningKeyInput_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubjectPublicKeyInfo.h"
#include "GeneralName.h"
#include "PKMACValue.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum authInfo_PR {
	authInfo_PR_NOTHING,	/* No components present */
	authInfo_PR_sender,
	authInfo_PR_publicKeyMAC
} authInfo_PR;

/* POPOSigningKeyInput */
typedef struct POPOSigningKeyInput {
	struct authInfo {
		authInfo_PR present;
		union POPOSigningKeyInput__authInfo_u {
			GeneralName_t	 sender;
			PKMACValue_t	 publicKeyMAC;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} authInfo;
	SubjectPublicKeyInfo_t	 publicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} POPOSigningKeyInput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_POPOSigningKeyInput;

#ifdef __cplusplus
}
#endif

#endif	/* _POPOSigningKeyInput_H_ */
