/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ProofOfPossession_H_
#define	_ProofOfPossession_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "POPOSigningKey.h"
#include "POPOPrivKey.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProofOfPossession_PR {
	ProofOfPossession_PR_NOTHING,	/* No components present */
	ProofOfPossession_PR_raVerified,
	ProofOfPossession_PR_signature,
	ProofOfPossession_PR_keyEncipherment,
	ProofOfPossession_PR_keyAgreement
} ProofOfPossession_PR;

/* ProofOfPossession */
typedef struct ProofOfPossession {
	ProofOfPossession_PR present;
	union ProofOfPossession_u {
		NULL_t	 raVerified;
		POPOSigningKey_t	 signature;
		POPOPrivKey_t	 keyEncipherment;
		POPOPrivKey_t	 keyAgreement;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProofOfPossession_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProofOfPossession;

#ifdef __cplusplus
}
#endif

#endif	/* _ProofOfPossession_H_ */
