/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ProtocolEncrKey_H_
#define	_ProtocolEncrKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubjectPublicKeyInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolEncrKey */
typedef SubjectPublicKeyInfo_t	 ProtocolEncrKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolEncrKey;
asn_struct_free_f ProtocolEncrKey_free;
asn_struct_print_f ProtocolEncrKey_print;
asn_constr_check_f ProtocolEncrKey_constraint;
ber_type_decoder_f ProtocolEncrKey_decode_ber;
der_type_encoder_f ProtocolEncrKey_encode_der;
xer_type_decoder_f ProtocolEncrKey_decode_xer;
xer_type_encoder_f ProtocolEncrKey_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolEncrKey_H_ */
