/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ReceiptsFrom_H_
#define	_ReceiptsFrom_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AllOrFirstTier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReceiptsFrom_PR {
	ReceiptsFrom_PR_NOTHING,	/* No components present */
	ReceiptsFrom_PR_allOrFirstTier,
	ReceiptsFrom_PR_receiptList
} ReceiptsFrom_PR;

/* Forward declarations */
struct GeneralNames;

/* ReceiptsFrom */
typedef struct ReceiptsFrom {
	ReceiptsFrom_PR present;
	union ReceiptsFrom_u {
		AllOrFirstTier_t	 allOrFirstTier;
		struct receiptList {
			A_SEQUENCE_OF(struct GeneralNames) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} receiptList;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptsFrom_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptsFrom;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralNames.h"

#endif	/* _ReceiptsFrom_H_ */
