/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ReceiptRequest_H_
#define	_ReceiptRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ContentIdentifier.h"
#include "ReceiptsFrom.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralNames;

/* ReceiptRequest */
typedef struct ReceiptRequest {
	ContentIdentifier_t	 signedContentIdentifier;
	ReceiptsFrom_t	 receiptsFrom;
	struct receiptsTo {
		A_SEQUENCE_OF(struct GeneralNames) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} receiptsTo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralNames.h"

#endif	/* _ReceiptRequest_H_ */
