/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RecipientKeyIdentifier_H_
#define	_RecipientKeyIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSSubjectKeyIdentifier.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OtherKeyAttribute;

/* RecipientKeyIdentifier */
typedef struct RecipientKeyIdentifier {
	CMSSubjectKeyIdentifier_t	 subjectKeyIdentifier;
	GeneralizedTime_t	*date	/* OPTIONAL */;
	struct OtherKeyAttribute	*other	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecipientKeyIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecipientKeyIdentifier;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OtherKeyAttribute.h"

#endif	/* _RecipientKeyIdentifier_H_ */
