/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RegToken_H_
#define	_RegToken_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RegToken */
typedef UTF8String_t	 RegToken_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegToken;
asn_struct_free_f RegToken_free;
asn_struct_print_f RegToken_print;
asn_constr_check_f RegToken_constraint;
ber_type_decoder_f RegToken_decode_ber;
der_type_encoder_f RegToken_encode_der;
xer_type_decoder_f RegToken_decode_xer;
xer_type_encoder_f RegToken_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RegToken_H_ */
