/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ResponseData_H_
#define	_ResponseData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OCSP-Version.h"
#include "ResponderID.h"
#include <GeneralizedTime.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;
struct SingleResponse;

/* ResponseData */
typedef struct ResponseData {
	OCSP_Version_t	 version	/* DEFAULT 0 */;
	ResponderID_t	 responderID;
	GeneralizedTime_t	 producedAt;
	struct responses {
		A_SEQUENCE_OF(struct SingleResponse) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} responses;
	struct Extensions	*responseExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"
#include "SingleResponse.h"

#endif	/* _ResponseData_H_ */
