/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevAnnContent_H_
#define	_RevAnnContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKIStatus.h"
#include "CertId.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;

/* RevAnnContent */
typedef struct RevAnnContent {
	PKIStatus_t	 status;
	CertID_t	 certId;
	GeneralizedTime_t	 willBeRevokedAt;
	GeneralizedTime_t	 badSinceDate;
	struct Extensions	*crlDetails	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevAnnContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevAnnContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"

#endif	/* _RevAnnContent_H_ */
