/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevDetails_H_
#define	_RevDetails_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertTemplate.h"
#include "ReasonFlags.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;

/* RevDetails */
typedef struct RevDetails {
	CertTemplate_t	 certDetails;
	ReasonFlags_t	*revocationReason	/* OPTIONAL */;
	GeneralizedTime_t	*badSinceDate	/* OPTIONAL */;
	struct Extensions	*crlEntryDetails	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevDetails;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"

#endif	/* _RevDetails_H_ */
