/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevocationValues_H_
#define	_RevocationValues_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OtherRevVals.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateList;
struct BasicOCSPResponse;

/* RevocationValues */
typedef struct RevocationValues {
	struct crlVals {
		A_SEQUENCE_OF(struct CertificateList) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crlVals;
	struct ocspVals {
		A_SEQUENCE_OF(struct BasicOCSPResponse) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ocspVals;
	OtherRevVals_t	 otherRevVals;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevocationValues_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevocationValues;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateList.h"
#include "BasicOCSPResponse.h"

#endif	/* _RevocationValues_H_ */
