/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevReqContent_H_
#define	_RevReqContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RevDetails;

/* RevReqContent */
typedef struct RevReqContent {
	A_SEQUENCE_OF(struct RevDetails) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevReqContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevReqContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RevDetails.h"

#endif	/* _RevReqContent_H_ */
