/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevRepContent_H_
#define	_RevRepContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKIStatusInfo;
struct CertId;
struct CertificateList;

/* RevRepContent */
typedef struct RevRepContent {
	struct status {
		A_SEQUENCE_OF(struct PKIStatusInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} status;
	struct revCerts {
		A_SEQUENCE_OF(struct CertId) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *revCerts;
	struct crls {
		A_SEQUENCE_OF(struct CertificateList) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crls;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevRepContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevRepContent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PKIStatusInfo.h"
#include "CertId.h"
#include "CertificateList.h"

#endif	/* _RevRepContent_H_ */
