/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevReq_H_
#define	_RevReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EnuRevReq.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignPolExtensions;

/* RevReq */
typedef struct RevReq {
	EnuRevReq_t	 enuRevReq;
	struct SignPolExtensions	*exRevReq	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevReq;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignPolExtensions.h"

#endif	/* _RevReq_H_ */
