/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SecurityCategories_H_
#define	_SecurityCategories_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ESS_SecurityCategory;

/* SecurityCategories */
typedef struct SecurityCategories {
	A_SET_OF(struct ESS_SecurityCategory) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityCategories_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityCategories;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ESS-SecurityCategory.h"

#endif	/* _SecurityCategories_H_ */
