/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SecurityPolicyIdentifier_H_
#define	_SecurityPolicyIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityPolicyIdentifier */
typedef OBJECT_IDENTIFIER_t	 SecurityPolicyIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityPolicyIdentifier;
asn_struct_free_f SecurityPolicyIdentifier_free;
asn_struct_print_f SecurityPolicyIdentifier_print;
asn_constr_check_f SecurityPolicyIdentifier_constraint;
ber_type_decoder_f SecurityPolicyIdentifier_decode_ber;
der_type_encoder_f SecurityPolicyIdentifier_encode_der;
xer_type_decoder_f SecurityPolicyIdentifier_decode_xer;
xer_type_encoder_f SecurityPolicyIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityPolicyIdentifier_H_ */
