/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SecurityClassification_H_
#define	_SecurityClassification_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityClassification {
	SecurityClassification_unmarked	= 0,
	SecurityClassification_unclassified	= 1,
	SecurityClassification_restricted	= 2,
	SecurityClassification_confidential	= 3,
	SecurityClassification_secret	= 4,
	SecurityClassification_top_secret	= 5
} e_SecurityClassification;

/* SecurityClassification */
typedef long	 SecurityClassification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityClassification;
asn_struct_free_f SecurityClassification_free;
asn_struct_print_f SecurityClassification_print;
asn_constr_check_f SecurityClassification_constraint;
ber_type_decoder_f SecurityClassification_decode_ber;
der_type_encoder_f SecurityClassification_encode_der;
xer_type_decoder_f SecurityClassification_decode_xer;
xer_type_encoder_f SecurityClassification_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityClassification_H_ */
