/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SelectedCommitmentTypes_H_
#define	_SelectedCommitmentTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NULL.h>
#include "CommitmentType.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Member_PR {
	Member_PR_NOTHING,	/* No components present */
	Member_PR_empty,
	Member_PR_recognizedCommitmentType
} Member_PR;

typedef struct  {
	Member_PR present;
	union SelectedCommitmentTypes__Member_u {
		NULL_t	 empty;
		CommitmentType_t	 recognizedCommitmentType;
	} choice;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
}  SelectedCommitmentTypes_Member_t;

/* SelectedCommitmentTypes */
typedef struct SelectedCommitmentTypes {
	A_SEQUENCE_OF(SelectedCommitmentTypes_Member_t) list;

	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SelectedCommitmentTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SelectedCommitmentTypes;

#ifdef __cplusplus
}
#endif

#endif	/* _SelectedCommitmentTypes_H_ */
