/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignerAttribute_H_
#define	_SignerAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ClaimedAttributes.h"
#include "CertifiedAttributes.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Member_PR {
	Member_PR_NOTHING,	/* No components present */
	Member_PR_claimedAttributes,
	Member_PR_certifiedAttributes
} Member_PR;

/* SignerAttribute */
typedef struct SignerAttribute {
	A_SEQUENCE_OF(struct Member {
		Member_PR present;
		union SignerAttribute__Member_u {
			ClaimedAttributes_t	 claimedAttributes;
			CertifiedAttributes_t	 certifiedAttributes;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerAttribute_H_ */
