/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SigningCertTrustCondition_H_
#define	_SigningCertTrustCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertificateTrustTrees.h"
#include "CertRevReq.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SigningCertTrustCondition */
typedef struct SigningCertTrustCondition {
	CertificateTrustTrees_t	 signerTrustTrees;
	CertRevReq_t	 signerRevReq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigningCertTrustCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigningCertTrustCondition;

#ifdef __cplusplus
}
#endif

#endif	/* _SigningCertTrustCondition_H_ */
