/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SigningPeriod_H_
#define	_SigningPeriod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SigningPeriod */
typedef struct SigningPeriod {
	GeneralizedTime_t	 notBefore;
	GeneralizedTime_t	*notAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigningPeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigningPeriod;

#ifdef __cplusplus
}
#endif

#endif	/* _SigningPeriod_H_ */
