/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignPolicyId_H_
#define	_SignPolicyId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignPolicyId */
typedef OBJECT_IDENTIFIER_t	 SignPolicyId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignPolicyId;
asn_struct_free_f SignPolicyId_free;
asn_struct_print_f SignPolicyId_print;
asn_constr_check_f SignPolicyId_constraint;
ber_type_decoder_f SignPolicyId_decode_ber;
der_type_encoder_f SignPolicyId_encode_der;
xer_type_decoder_f SignPolicyId_decode_xer;
xer_type_encoder_f SignPolicyId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignPolicyId_H_ */
