/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignatureValidationPolicy_H_
#define	_SignatureValidationPolicy_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SigningPeriod.h"
#include "CommonRules.h"
#include "CommitmentRules.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignPolExtensions;

/* SignatureValidationPolicy */
typedef struct SignatureValidationPolicy {
	SigningPeriod_t	 signingPeriod;
	CommonRules_t	 commonRules;
	CommitmentRules_t	 commitmentRules;
	struct SignPolExtensions	*signPolExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignatureValidationPolicy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignatureValidationPolicy;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignPolExtensions.h"

#endif	/* _SignatureValidationPolicy_H_ */
