/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignerLocation_H_
#define	_SignerLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DirectoryString;
struct PostalAddress;

/* SignerLocation */
typedef struct SignerLocation {
	struct DirectoryString	*countryName	/* OPTIONAL */;
	struct DirectoryString	*localityName	/* OPTIONAL */;
	struct PostalAddress	*postalAdddress	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerLocation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DirectoryString.h"
#include "PostalAddress.h"

#endif	/* _SignerLocation_H_ */
