/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignerAndVerifierRules_H_
#define	_SignerAndVerifierRules_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignerRules.h"
#include "VerifierRules.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignerAndVerifierRules */
typedef struct SignerAndVerifierRules {
	SignerRules_t	 signerRules;
	VerifierRules_t	 verifierRules;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerAndVerifierRules_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerAndVerifierRules;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerAndVerifierRules_H_ */
