/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SinglePubInfo_H_
#define	_SinglePubInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum pubMethod {
	pubMethod_dontCare	= 0,
	pubMethod_x500	= 1,
	pubMethod_web	= 2,
	pubMethod_ldap	= 3
} e_pubMethod;

/* Forward declarations */
struct GeneralName;

/* SinglePubInfo */
typedef struct SinglePubInfo {
	long	 pubMethod;
	struct GeneralName	*pubLocation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SinglePubInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SinglePubInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralName.h"

#endif	/* _SinglePubInfo_H_ */
