/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SingleResponse_H_
#define	_SingleResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertID.h"
#include "CertStatus.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;

/* SingleResponse */
typedef struct SingleResponse {
	CertID_t	 certID;
	CertStatus_t	 certStatus;
	GeneralizedTime_t	 thisUpdate;
	GeneralizedTime_t	*nextUpdate	/* OPTIONAL */;
	struct Extensions	*singleExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SingleResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SingleResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"

#endif	/* _SingleResponse_H_ */
