/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SubsequentMessage_H_
#define	_SubsequentMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubsequentMessage {
	SubsequentMessage_encrCert	= 0,
	SubsequentMessage_challengeResp	= 1
} e_SubsequentMessage;

/* SubsequentMessage */
typedef long	 SubsequentMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubsequentMessage;
asn_struct_free_f SubsequentMessage_free;
asn_struct_print_f SubsequentMessage_print;
asn_constr_check_f SubsequentMessage_constraint;
ber_type_decoder_f SubsequentMessage_decode_ber;
der_type_encoder_f SubsequentMessage_encode_der;
xer_type_decoder_f SubsequentMessage_decode_xer;
xer_type_encoder_f SubsequentMessage_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SubsequentMessage_H_ */
