/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TimestampTrustCondition_H_
#define	_TimestampTrustCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateTrustTrees;
struct CertRevReq;
struct NameConstraints;
struct DeltaTime;

/* TimestampTrustCondition */
typedef struct TimestampTrustCondition {
	struct CertificateTrustTrees	*ttsCertificateTrustTrees	/* OPTIONAL */;
	struct CertRevReq	*ttsRevReq	/* OPTIONAL */;
	struct NameConstraints	*ttsNameConstraints	/* OPTIONAL */;
	struct DeltaTime	*cautionPeriod	/* OPTIONAL */;
	struct DeltaTime	*signatureTimestampDelay	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimestampTrustCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimestampTrustCondition;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateTrustTrees.h"
#include "CertRevReq.h"
#include "NameConstraints.h"
#include "DeltaTime.h"

#endif	/* _TimestampTrustCondition_H_ */
