/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TimeStampReq_H_
#define	_TimeStampReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "MessageImprint.h"
#include "TSAPolicyId.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

#ifdef e_version
	typedef extern enum version {
		version_v1 = 1
	} e_version;
#endif

/* Forward declarations */
struct Extensions;

/* TimeStampReq */
typedef struct TimeStampReq {
	long	 version;
	MessageImprint_t	 messageImprint;
	TSAPolicyId_t	*reqPolicy	/* OPTIONAL */;
	long	*nonce	/* OPTIONAL */;
	BOOLEAN_t	*certReq	/* DEFAULT FALSE */;
	struct Extensions	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeStampReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeStampReq;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extensions.h"

#endif	/* _TimeStampReq_H_ */
