/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_TimeReferenceType_H_
#define	_TimeReferenceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeReferenceType {
	TimeReferenceType_tu	= 0,
	TimeReferenceType_ts	= 1
} e_TimeReferenceType;

/* TimeReferenceType */
typedef long	 TimeReferenceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeReferenceType;
asn_struct_free_f TimeReferenceType_free;
asn_struct_print_f TimeReferenceType_print;
asn_constr_check_f TimeReferenceType_constraint;
ber_type_decoder_f TimeReferenceType_decode_ber;
der_type_encoder_f TimeReferenceType_encode_der;
xer_type_decoder_f TimeReferenceType_decode_xer;
xer_type_encoder_f TimeReferenceType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeReferenceType_H_ */
