/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Validity_H_
#define	_Validity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Validity */
typedef struct Validity {
	Time_t	 notBefore;
	Time_t	 notAfter;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Validity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Validity;

#ifdef __cplusplus
}
#endif

#endif	/* _Validity_H_ */
