/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_VriDictionary_H_
#define	_VriDictionary_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PdfEntry;
//typedef struct mandatedEntries;

/* VriDictionary */
typedef struct VriDictionary {
	struct _mandatedEntries {
		A_SEQUENCE_OF(struct PdfEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} _mandatedEntries;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VriDictionary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VriDictionary;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PdfEntry.h"

#endif	/* _VriDictionary_H_ */
