/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_VriDictionary_H_
#define	_VriDictionary_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PdfEntry.h"
#include "TimeReferenceType.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VriDictionary */
typedef struct VriDictionary {
	PdfEntry_t	 type;
	TimeReferenceType_t	*timeReference	/* OPTIONAL */;
	BOOLEAN_t	*paArtifacts	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VriDictionary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VriDictionary;

#ifdef __cplusplus
}
#endif

#endif	/* _VriDictionary_H_ */
