/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "AlgAndLength.h"

static asn_TYPE_member_t asn_MBR_AlgAndLength_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlgAndLength, algID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"algID"
		},
	{ ATF_POINTER, 2, offsetof(struct AlgAndLength, minKeyLength),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minKeyLength"
		},
	{ ATF_POINTER, 1, offsetof(struct AlgAndLength, signPolExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SignPolExtensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signPolExtensions"
		},
};
static ber_tlv_tag_t asn_DEF_AlgAndLength_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AlgAndLength_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* minKeyLength at 1193 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* algID at 1192 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* signPolExtensions at 1195 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AlgAndLength_specs_1 = {
	sizeof(struct AlgAndLength),
	offsetof(struct AlgAndLength, _asn_ctx),
	asn_MAP_AlgAndLength_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AlgAndLength = {
	"AlgAndLength",
	"AlgAndLength",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AlgAndLength_tags_1,
	sizeof(asn_DEF_AlgAndLength_tags_1)
		/sizeof(asn_DEF_AlgAndLength_tags_1[0]), /* 1 */
	asn_DEF_AlgAndLength_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlgAndLength_tags_1)
		/sizeof(asn_DEF_AlgAndLength_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AlgAndLength_1,
	3,	/* Elements count */
	&asn_SPC_AlgAndLength_specs_1	/* Additional specs */
};

