/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "CertificationRequestInfo.h"

static asn_TYPE_member_t asn_MBR_CertificationRequestInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertificationRequestInfo, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificationRequestInfo, subject),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Name,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificationRequestInfo, subjectPKInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SubjectPublicKeyInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subjectPKInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificationRequestInfo, attributes),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Attributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attributes"
		},
};
static ber_tlv_tag_t asn_DEF_CertificationRequestInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CertificationRequestInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 2400 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* rdnSequence at 544 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 }, /* subjectPKInfo at 2402 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 } /* attributes at 2404 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CertificationRequestInfo_specs_1 = {
	sizeof(struct CertificationRequestInfo),
	offsetof(struct CertificationRequestInfo, _asn_ctx),
	asn_MAP_CertificationRequestInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CertificationRequestInfo = {
	"CertificationRequestInfo",
	"CertificationRequestInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CertificationRequestInfo_tags_1,
	sizeof(asn_DEF_CertificationRequestInfo_tags_1)
		/sizeof(asn_DEF_CertificationRequestInfo_tags_1[0]), /* 1 */
	asn_DEF_CertificationRequestInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CertificationRequestInfo_tags_1)
		/sizeof(asn_DEF_CertificationRequestInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CertificationRequestInfo_1,
	4,	/* Elements count */
	&asn_SPC_CertificationRequestInfo_specs_1	/* Additional specs */
};

