/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "Challenge.h"

static asn_TYPE_member_t asn_MBR_Challenge_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Challenge, owf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"owf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Challenge, witness),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"witness"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Challenge, challenge),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"challenge"
		},
};
static ber_tlv_tag_t asn_DEF_Challenge_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Challenge_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 1 }, /* witness at 2529 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -1, 0 }, /* challenge at 2533 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* owf at 2524 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Challenge_specs_1 = {
	sizeof(struct Challenge),
	offsetof(struct Challenge, _asn_ctx),
	asn_MAP_Challenge_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Challenge = {
	"Challenge",
	"Challenge",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Challenge_tags_1,
	sizeof(asn_DEF_Challenge_tags_1)
		/sizeof(asn_DEF_Challenge_tags_1[0]), /* 1 */
	asn_DEF_Challenge_tags_1,	/* Same as above */
	sizeof(asn_DEF_Challenge_tags_1)
		/sizeof(asn_DEF_Challenge_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Challenge_1,
	3,	/* Elements count */
	&asn_SPC_Challenge_specs_1	/* Additional specs */
};

