/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "C:\Users\Luiz\Documents\lpa22.asn1"
 */

#include <asn_internal.h>

#include "DssDictionary.h"

static asn_TYPE_member_t asn_MBR_mandatedEntries_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PdfEntry,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_mandatedEntries_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mandatedEntries_specs_2 = {
	sizeof(struct mandatedEntries),
	offsetof(struct mandatedEntries, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mandatedEntries_2 = {
	"mandatedEntries",
	"mandatedEntries",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mandatedEntries_tags_2,
	sizeof(asn_DEF_mandatedEntries_tags_2)
		/sizeof(asn_DEF_mandatedEntries_tags_2[0]), /* 1 */
	asn_DEF_mandatedEntries_tags_2,	/* Same as above */
	sizeof(asn_DEF_mandatedEntries_tags_2)
		/sizeof(asn_DEF_mandatedEntries_tags_2[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_mandatedEntries_2,
	1,	/* Single element */
	&asn_SPC_mandatedEntries_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vriMandatedEntries_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PdfEntry,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_vriMandatedEntries_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_vriMandatedEntries_specs_4 = {
	sizeof(struct vriMandatedEntries),
	offsetof(struct vriMandatedEntries, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vriMandatedEntries_4 = {
	"vriMandatedEntries",
	"vriMandatedEntries",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vriMandatedEntries_tags_4,
	sizeof(asn_DEF_vriMandatedEntries_tags_4)
		/sizeof(asn_DEF_vriMandatedEntries_tags_4[0]), /* 1 */
	asn_DEF_vriMandatedEntries_tags_4,	/* Same as above */
	sizeof(asn_DEF_vriMandatedEntries_tags_4)
		/sizeof(asn_DEF_vriMandatedEntries_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_vriMandatedEntries_4,
	1,	/* Single element */
	&asn_SPC_vriMandatedEntries_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DssDictionary_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DssDictionary, mandatedEntries),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_mandatedEntries_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mandatedEntries"
		},
	{ ATF_POINTER, 1, offsetof(struct DssDictionary, vriMandatedEntries),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_vriMandatedEntries_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vriMandatedEntries"
		},
};
static ber_tlv_tag_t asn_DEF_DssDictionary_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DssDictionary_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* mandatedEntries at 1216 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* vriMandatedEntries at 1217 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DssDictionary_specs_1 = {
	sizeof(struct DssDictionary),
	offsetof(struct DssDictionary, _asn_ctx),
	asn_MAP_DssDictionary_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DssDictionary = {
	"DssDictionary",
	"DssDictionary",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DssDictionary_tags_1,
	sizeof(asn_DEF_DssDictionary_tags_1)
		/sizeof(asn_DEF_DssDictionary_tags_1[0]), /* 1 */
	asn_DEF_DssDictionary_tags_1,	/* Same as above */
	sizeof(asn_DEF_DssDictionary_tags_1)
		/sizeof(asn_DEF_DssDictionary_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DssDictionary_1,
	2,	/* Elements count */
	&asn_SPC_DssDictionary_specs_1	/* Additional specs */
};

DssDictionary_t*
DecodeDssDictionary(const void *buf, size_t size) {
	DssDictionary_t *dss = 0; /* Note this 0! */
	asn_dec_rval_t rval;
	rval = asn_DEF_DssDictionary.ber_decoder(0,
		&asn_DEF_DssDictionary,
		(void **)&dss,
		buf, size,
		0);

	if (rval.code == RC_OK)
		return dss;
	
	DssDictionary_free(dss);
	return 0;
}

void
 DssDictionary_free(DssDictionary_t *dss) {
	if (dss) {
		asn_DEF_DssDictionary.free_struct(
			&asn_DEF_DssDictionary, dss, 0);
	}
}
