/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "EntityIdentifier.h"

static asn_TYPE_member_t asn_MBR_EntityIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntityIdentifier, choice.issuerAndSerialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IssuerAndSerialNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuerAndSerialNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntityIdentifier, choice.subjectKeyIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subjectKeyIdentifier"
		},
};
static asn_TYPE_tag2member_t asn_MAP_EntityIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* subjectKeyIdentifier at 3101 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* issuerAndSerialNumber at 3100 */
};
static asn_CHOICE_specifics_t asn_SPC_EntityIdentifier_specs_1 = {
	sizeof(struct EntityIdentifier),
	offsetof(struct EntityIdentifier, _asn_ctx),
	offsetof(struct EntityIdentifier, present),
	sizeof(((struct EntityIdentifier *)0)->present),
	asn_MAP_EntityIdentifier_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EntityIdentifier = {
	"EntityIdentifier",
	"EntityIdentifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_EntityIdentifier_1,
	2,	/* Elements count */
	&asn_SPC_EntityIdentifier_specs_1	/* Additional specs */
};

