/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "ESS-SecurityCategory.h"

static asn_TYPE_member_t asn_MBR_ESS_SecurityCategory_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ESS_SecurityCategory, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ESS_SecurityCategory, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
};
static ber_tlv_tag_t asn_DEF_ESS_SecurityCategory_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ESS_SecurityCategory_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type at 3063 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value at 3064 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ESS_SecurityCategory_specs_1 = {
	sizeof(struct ESS_SecurityCategory),
	offsetof(struct ESS_SecurityCategory, _asn_ctx),
	asn_MAP_ESS_SecurityCategory_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ESS_SecurityCategory = {
	"ESS-SecurityCategory",
	"ESS-SecurityCategory",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ESS_SecurityCategory_tags_1,
	sizeof(asn_DEF_ESS_SecurityCategory_tags_1)
		/sizeof(asn_DEF_ESS_SecurityCategory_tags_1[0]), /* 1 */
	asn_DEF_ESS_SecurityCategory_tags_1,	/* Same as above */
	sizeof(asn_DEF_ESS_SecurityCategory_tags_1)
		/sizeof(asn_DEF_ESS_SecurityCategory_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ESS_SecurityCategory_1,
	2,	/* Elements count */
	&asn_SPC_ESS_SecurityCategory_specs_1	/* Additional specs */
};

