/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "ESSSecurityLabel.h"

static asn_TYPE_member_t asn_MBR_ESSSecurityLabel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ESSSecurityLabel, security_policy_identifier),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_SecurityPolicyIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"security-policy-identifier"
		},
	{ ATF_POINTER, 3, offsetof(struct ESSSecurityLabel, security_classification),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SecurityClassification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"security-classification"
		},
	{ ATF_POINTER, 2, offsetof(struct ESSSecurityLabel, privacy_mark),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ESSPrivacyMark,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"privacy-mark"
		},
	{ ATF_POINTER, 1, offsetof(struct ESSSecurityLabel, security_categories),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_SecurityCategories,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"security-categories"
		},
};
static ber_tlv_tag_t asn_DEF_ESSSecurityLabel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ESSSecurityLabel_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* security-classification at 3033 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* security-policy-identifier at 3032 */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, 0, 0 }, /* utf8String at 3052 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 3, 0, 0 }, /* security-categories at 3035 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, 0, 0 } /* pString at 3051 */
};
static asn_TYPE_tag2member_t asn_MAP_ESSSecurityLabel_tag2el_cxer_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* security-classification at 3033 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* security-policy-identifier at 3032 */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, 0, 0 }, /* utf8String at 3052 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 3, 0, 0 } /* security-categories at 3035 */
};
static uint8_t asn_MAP_ESSSecurityLabel_mmap_1[(4 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (0 << 4)
};
static asn_SET_specifics_t asn_SPC_ESSSecurityLabel_specs_1 = {
	sizeof(struct ESSSecurityLabel),
	offsetof(struct ESSSecurityLabel, _asn_ctx),
	offsetof(struct ESSSecurityLabel, _presence_map),
	asn_MAP_ESSSecurityLabel_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ESSSecurityLabel_tag2el_cxer_1,
	4,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_ESSSecurityLabel_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_ESSSecurityLabel = {
	"ESSSecurityLabel",
	"ESSSecurityLabel",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ESSSecurityLabel_tags_1,
	sizeof(asn_DEF_ESSSecurityLabel_tags_1)
		/sizeof(asn_DEF_ESSSecurityLabel_tags_1[0]), /* 1 */
	asn_DEF_ESSSecurityLabel_tags_1,	/* Same as above */
	sizeof(asn_DEF_ESSSecurityLabel_tags_1)
		/sizeof(asn_DEF_ESSSecurityLabel_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ESSSecurityLabel_1,
	4,	/* Elements count */
	&asn_SPC_ESSSecurityLabel_specs_1	/* Additional specs */
};

