/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "MLReceiptPolicy.h"

static int
memb_insteadOf_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_inAdditionTo_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_insteadOf_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_insteadOf_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_insteadOf_specs_3 = {
	sizeof(struct insteadOf),
	offsetof(struct insteadOf, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_insteadOf_3 = {
	"insteadOf",
	"insteadOf",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_insteadOf_tags_3,
	sizeof(asn_DEF_insteadOf_tags_3)
		/sizeof(asn_DEF_insteadOf_tags_3[0]) - 1, /* 1 */
	asn_DEF_insteadOf_tags_3,	/* Same as above */
	sizeof(asn_DEF_insteadOf_tags_3)
		/sizeof(asn_DEF_insteadOf_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_insteadOf_3,
	1,	/* Single element */
	&asn_SPC_insteadOf_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_inAdditionTo_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_inAdditionTo_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_inAdditionTo_specs_5 = {
	sizeof(struct inAdditionTo),
	offsetof(struct inAdditionTo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_inAdditionTo_5 = {
	"inAdditionTo",
	"inAdditionTo",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_inAdditionTo_tags_5,
	sizeof(asn_DEF_inAdditionTo_tags_5)
		/sizeof(asn_DEF_inAdditionTo_tags_5[0]) - 1, /* 1 */
	asn_DEF_inAdditionTo_tags_5,	/* Same as above */
	sizeof(asn_DEF_inAdditionTo_tags_5)
		/sizeof(asn_DEF_inAdditionTo_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_inAdditionTo_5,
	1,	/* Single element */
	&asn_SPC_inAdditionTo_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MLReceiptPolicy_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MLReceiptPolicy, choice.none),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"none"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MLReceiptPolicy, choice.insteadOf),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_insteadOf_3,
		memb_insteadOf_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"insteadOf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MLReceiptPolicy, choice.inAdditionTo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_inAdditionTo_5,
		memb_inAdditionTo_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"inAdditionTo"
		},
};
static asn_TYPE_tag2member_t asn_MAP_MLReceiptPolicy_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* none at 3104 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* insteadOf at 3105 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* inAdditionTo at 3106 */
};
static asn_CHOICE_specifics_t asn_SPC_MLReceiptPolicy_specs_1 = {
	sizeof(struct MLReceiptPolicy),
	offsetof(struct MLReceiptPolicy, _asn_ctx),
	offsetof(struct MLReceiptPolicy, present),
	sizeof(((struct MLReceiptPolicy *)0)->present),
	asn_MAP_MLReceiptPolicy_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MLReceiptPolicy = {
	"MLReceiptPolicy",
	"MLReceiptPolicy",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MLReceiptPolicy_1,
	3,	/* Elements count */
	&asn_SPC_MLReceiptPolicy_specs_1	/* Additional specs */
};

