/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "PKIHeader.h"

static int
memb_generalInfo_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_generalInfo_14[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_InfoTypeAndValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_generalInfo_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_generalInfo_specs_14 = {
	sizeof(struct generalInfo),
	offsetof(struct generalInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_generalInfo_14 = {
	"generalInfo",
	"generalInfo",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_generalInfo_tags_14,
	sizeof(asn_DEF_generalInfo_tags_14)
		/sizeof(asn_DEF_generalInfo_tags_14[0]), /* 2 */
	asn_DEF_generalInfo_tags_14,	/* Same as above */
	sizeof(asn_DEF_generalInfo_tags_14)
		/sizeof(asn_DEF_generalInfo_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_generalInfo_14,
	1,	/* Single element */
	&asn_SPC_generalInfo_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PKIHeader_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PKIHeader, pvno),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pvno"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PKIHeader, sender),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sender"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PKIHeader, recipient),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipient"
		},
	{ ATF_POINTER, 9, offsetof(struct PKIHeader, messageTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageTime"
		},
	{ ATF_POINTER, 8, offsetof(struct PKIHeader, protectionAlg),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protectionAlg"
		},
	{ ATF_POINTER, 7, offsetof(struct PKIHeader, senderKID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KeyIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"senderKID"
		},
	{ ATF_POINTER, 6, offsetof(struct PKIHeader, recipKID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KeyIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipKID"
		},
	{ ATF_POINTER, 5, offsetof(struct PKIHeader, transactionID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionID"
		},
	{ ATF_POINTER, 4, offsetof(struct PKIHeader, senderNonce),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"senderNonce"
		},
	{ ATF_POINTER, 3, offsetof(struct PKIHeader, recipNonce),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipNonce"
		},
	{ ATF_POINTER, 2, offsetof(struct PKIHeader, freeText),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PKIFreeText,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"freeText"
		},
	{ ATF_POINTER, 1, offsetof(struct PKIHeader, generalInfo),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_generalInfo_14,
		memb_generalInfo_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generalInfo"
		},
};
static ber_tlv_tag_t asn_DEF_PKIHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PKIHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* pvno at 2328 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 2 }, /* otherName at 1476 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, -1, 1 }, /* otherName at 1476 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, -2, 0 }, /* messageTime at 2333 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 2 }, /* rfc822Name at 1477 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, -1, 1 }, /* rfc822Name at 1477 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, -2, 0 }, /* protectionAlg at 2337 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 2 }, /* dNSName at 1478 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, -1, 1 }, /* dNSName at 1478 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 5, -2, 0 }, /* senderKID at 2339 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 2 }, /* x400Address at 1479 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, -1, 1 }, /* x400Address at 1479 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 6, -2, 0 }, /* recipKID at 2340 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 2 }, /* directoryName at 1480 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, -1, 1 }, /* directoryName at 1480 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 7, -2, 0 }, /* transactionID at 2342 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 2 }, /* ediPartyName at 1481 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, -1, 1 }, /* ediPartyName at 1481 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 8, -2, 0 }, /* senderNonce at 2345 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 2 }, /* uniformResourceIdentifier at 1482 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 2, -1, 1 }, /* uniformResourceIdentifier at 1482 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 9, -2, 0 }, /* recipNonce at 2346 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 2 }, /* iPAddress at 1483 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 2, -1, 1 }, /* iPAddress at 1483 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 10, -2, 0 }, /* freeText at 2351 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 1, 0, 2 }, /* registeredID at 1484 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 2, -1, 1 }, /* registeredID at 1484 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 11, -2, 0 } /* generalInfo at 2355 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PKIHeader_specs_1 = {
	sizeof(struct PKIHeader),
	offsetof(struct PKIHeader, _asn_ctx),
	asn_MAP_PKIHeader_tag2el_1,
	28,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PKIHeader = {
	"PKIHeader",
	"PKIHeader",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PKIHeader_tags_1,
	sizeof(asn_DEF_PKIHeader_tags_1)
		/sizeof(asn_DEF_PKIHeader_tags_1[0]), /* 1 */
	asn_DEF_PKIHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_PKIHeader_tags_1)
		/sizeof(asn_DEF_PKIHeader_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PKIHeader_1,
	12,	/* Elements count */
	&asn_SPC_PKIHeader_specs_1	/* Additional specs */
};

