/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "PKIMessage.h"

static int
memb_extraCerts_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_extraCerts_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_extraCerts_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extraCerts_specs_5 = {
	sizeof(struct extraCerts),
	offsetof(struct extraCerts, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extraCerts_5 = {
	"extraCerts",
	"extraCerts",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_extraCerts_tags_5,
	sizeof(asn_DEF_extraCerts_tags_5)
		/sizeof(asn_DEF_extraCerts_tags_5[0]), /* 2 */
	asn_DEF_extraCerts_tags_5,	/* Same as above */
	sizeof(asn_DEF_extraCerts_tags_5)
		/sizeof(asn_DEF_extraCerts_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_extraCerts_5,
	1,	/* Single element */
	&asn_SPC_extraCerts_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PKIMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PKIMessage, header),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PKIHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header"
		},
	{ ATF_POINTER, 0, offsetof(struct PKIMessage, body),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PKIBody,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"body"
		},
	{ ATF_POINTER, 2, offsetof(struct PKIMessage, protection),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PKIProtection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protection"
		},
	{ ATF_POINTER, 1, offsetof(struct PKIMessage, extraCerts),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_extraCerts_5,
		memb_extraCerts_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extraCerts"
		},
};
static ber_tlv_tag_t asn_DEF_PKIMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PKIMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* header at 2321 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 1 }, /* ir at 2367 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, -1, 0 }, /* protection at 2323 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 1 }, /* ip at 2368 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, -1, 0 }, /* extraCerts at 2324 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* cr at 2369 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* cp at 2370 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* p10cr at 2371 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* popdecc at 2372 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* popdecr at 2373 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 0 }, /* kur at 2374 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 1, 0, 0 }, /* kup at 2375 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 0 }, /* krr at 2376 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 1, 0, 0 }, /* krp at 2377 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 1, 0, 0 }, /* rr at 2378 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 }, /* rp at 2379 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 1, 0, 0 }, /* ccr at 2380 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 1, 0, 0 }, /* ccp at 2381 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 1, 0, 0 }, /* ckuann at 2382 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 1, 0, 0 }, /* cann at 2383 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* rann at 2384 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 }, /* crlann at 2385 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 1, 0, 0 }, /* conf at 2386 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 1, 0, 0 }, /* nested at 2387 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 1, 0, 0 }, /* genm at 2388 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 1, 0, 0 }, /* genp at 2389 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 1, 0, 0 } /* error at 2391 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PKIMessage_specs_1 = {
	sizeof(struct PKIMessage),
	offsetof(struct PKIMessage, _asn_ctx),
	asn_MAP_PKIMessage_tag2el_1,
	27,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PKIMessage = {
	"PKIMessage",
	"PKIMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PKIMessage_tags_1,
	sizeof(asn_DEF_PKIMessage_tags_1)
		/sizeof(asn_DEF_PKIMessage_tags_1[0]), /* 1 */
	asn_DEF_PKIMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_PKIMessage_tags_1)
		/sizeof(asn_DEF_PKIMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PKIMessage_1,
	4,	/* Elements count */
	&asn_SPC_PKIMessage_specs_1	/* Additional specs */
};

