/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ListaDePAsAprovadasV2"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "PolicyInfo.h"

static asn_TYPE_member_t asn_MBR_PolicyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyInfo, signingPeriod),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SigningPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signingPeriod"
		},
	{ ATF_POINTER, 1, offsetof(struct PolicyInfo, revocationDate),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"revocationDate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyInfo, policyOID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policyOID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyInfo, policyURI),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policyURI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolicyInfo, policyDigest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OtherHashAlgAndValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policyDigest"
		},
};
static ber_tlv_tag_t asn_DEF_PolicyInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PolicyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 2, 0, 0 }, /* policyOID at 31 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* signingPeriod at 29 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 }, /* policyDigest at 33 */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 3, 0, 0 }, /* policyURI at 32 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 1, 0, 0 } /* revocationDate at 30 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PolicyInfo_specs_1 = {
	sizeof(struct PolicyInfo),
	offsetof(struct PolicyInfo, _asn_ctx),
	asn_MAP_PolicyInfo_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PolicyInfo = {
	"PolicyInfo",
	"PolicyInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PolicyInfo_tags_1,
	sizeof(asn_DEF_PolicyInfo_tags_1)
		/sizeof(asn_DEF_PolicyInfo_tags_1[0]), /* 1 */
	asn_DEF_PolicyInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_PolicyInfo_tags_1)
		/sizeof(asn_DEF_PolicyInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PolicyInfo_1,
	5,	/* Elements count */
	&asn_SPC_PolicyInfo_specs_1	/* Additional specs */
};

