/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "POPOSigningKey.h"

static asn_TYPE_member_t asn_MBR_POPOSigningKey_1[] = {
	{ ATF_POINTER, 1, offsetof(struct POPOSigningKey, poposkInput),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_POPOSigningKeyInput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"poposkInput"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct POPOSigningKey, algorithmIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"algorithmIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct POPOSigningKey, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signature"
		},
};
static ber_tlv_tag_t asn_DEF_POPOSigningKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_POPOSigningKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* signature at 2715 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* algorithmIdentifier at 2714 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* poposkInput at 2713 */
};
static asn_SEQUENCE_specifics_t asn_SPC_POPOSigningKey_specs_1 = {
	sizeof(struct POPOSigningKey),
	offsetof(struct POPOSigningKey, _asn_ctx),
	asn_MAP_POPOSigningKey_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_POPOSigningKey = {
	"POPOSigningKey",
	"POPOSigningKey",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_POPOSigningKey_tags_1,
	sizeof(asn_DEF_POPOSigningKey_tags_1)
		/sizeof(asn_DEF_POPOSigningKey_tags_1[0]), /* 1 */
	asn_DEF_POPOSigningKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_POPOSigningKey_tags_1)
		/sizeof(asn_DEF_POPOSigningKey_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_POPOSigningKey_1,
	3,	/* Elements count */
	&asn_SPC_POPOSigningKey_specs_1	/* Additional specs */
};

