/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCRMF"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "POPOPrivKey.h"

static asn_TYPE_member_t asn_MBR_POPOPrivKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct POPOPrivKey, choice.thisMessage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"thisMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct POPOPrivKey, choice.subsequentMessage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubsequentMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subsequentMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct POPOPrivKey, choice.dhMAC),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dhMAC"
		},
};
static asn_TYPE_tag2member_t asn_MAP_POPOPrivKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* thisMessage at 2792 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* subsequentMessage at 2795 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dhMAC at 2797 */
};
static asn_CHOICE_specifics_t asn_SPC_POPOPrivKey_specs_1 = {
	sizeof(struct POPOPrivKey),
	offsetof(struct POPOPrivKey, _asn_ctx),
	offsetof(struct POPOPrivKey, present),
	sizeof(((struct POPOPrivKey *)0)->present),
	asn_MAP_POPOPrivKey_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_POPOPrivKey = {
	"POPOPrivKey",
	"POPOPrivKey",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_POPOPrivKey_1,
	3,	/* Elements count */
	&asn_SPC_POPOPrivKey_specs_1	/* Additional specs */
};

