/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "ProtectedPart.h"

static asn_TYPE_member_t asn_MBR_ProtectedPart_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProtectedPart, header),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PKIHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtectedPart, body),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PKIBody,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"body"
		},
};
static ber_tlv_tag_t asn_DEF_ProtectedPart_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ProtectedPart_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* header at 2375 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* ir at 2331 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ip at 2332 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* cr at 2333 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* cp at 2334 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* p10cr at 2335 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* popdecc at 2336 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* popdecr at 2337 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 0 }, /* kur at 2338 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 1, 0, 0 }, /* kup at 2339 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 0 }, /* krr at 2340 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 1, 0, 0 }, /* krp at 2341 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 1, 0, 0 }, /* rr at 2342 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 }, /* rp at 2343 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 1, 0, 0 }, /* ccr at 2344 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 1, 0, 0 }, /* ccp at 2345 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 1, 0, 0 }, /* ckuann at 2346 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 1, 0, 0 }, /* cann at 2347 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* rann at 2348 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 }, /* crlann at 2349 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 1, 0, 0 }, /* conf at 2350 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 1, 0, 0 }, /* nested at 2351 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 1, 0, 0 }, /* genm at 2352 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 1, 0, 0 }, /* genp at 2353 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 1, 0, 0 } /* error at 2355 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ProtectedPart_specs_1 = {
	sizeof(struct ProtectedPart),
	offsetof(struct ProtectedPart, _asn_ctx),
	asn_MAP_ProtectedPart_tag2el_1,
	25,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ProtectedPart = {
	"ProtectedPart",
	"ProtectedPart",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProtectedPart_tags_1,
	sizeof(asn_DEF_ProtectedPart_tags_1)
		/sizeof(asn_DEF_ProtectedPart_tags_1[0]), /* 1 */
	asn_DEF_ProtectedPart_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtectedPart_tags_1)
		/sizeof(asn_DEF_ProtectedPart_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtectedPart_1,
	2,	/* Elements count */
	&asn_SPC_ProtectedPart_specs_1	/* Additional specs */
};

