/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "ReceiptRequest.h"

static int
memb_receiptsTo_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_receiptsTo_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_receiptsTo_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_receiptsTo_specs_4 = {
	sizeof(struct receiptsTo),
	offsetof(struct receiptsTo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_receiptsTo_4 = {
	"receiptsTo",
	"receiptsTo",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_receiptsTo_tags_4,
	sizeof(asn_DEF_receiptsTo_tags_4)
		/sizeof(asn_DEF_receiptsTo_tags_4[0]), /* 1 */
	asn_DEF_receiptsTo_tags_4,	/* Same as above */
	sizeof(asn_DEF_receiptsTo_tags_4)
		/sizeof(asn_DEF_receiptsTo_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_receiptsTo_4,
	1,	/* Single element */
	&asn_SPC_receiptsTo_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ReceiptRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReceiptRequest, signedContentIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ContentIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signedContentIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReceiptRequest, receiptsFrom),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ReceiptsFrom,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"receiptsFrom"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReceiptRequest, receiptsTo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_receiptsTo_4,
		memb_receiptsTo_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"receiptsTo"
		},
};
static ber_tlv_tag_t asn_DEF_ReceiptRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReceiptRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* signedContentIdentifier at 2935 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* receiptsTo at 2937 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* allOrFirstTier at 2950 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* receiptList at 2952 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReceiptRequest_specs_1 = {
	sizeof(struct ReceiptRequest),
	offsetof(struct ReceiptRequest, _asn_ctx),
	asn_MAP_ReceiptRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReceiptRequest = {
	"ReceiptRequest",
	"ReceiptRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReceiptRequest_tags_1,
	sizeof(asn_DEF_ReceiptRequest_tags_1)
		/sizeof(asn_DEF_ReceiptRequest_tags_1[0]), /* 1 */
	asn_DEF_ReceiptRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReceiptRequest_tags_1)
		/sizeof(asn_DEF_ReceiptRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReceiptRequest_1,
	3,	/* Elements count */
	&asn_SPC_ReceiptRequest_specs_1	/* Additional specs */
};

