/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ExtendedSecurityServices"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "Receipt.h"

static asn_TYPE_member_t asn_MBR_Receipt_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Receipt, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ESSVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Receipt, contentType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_ContentType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Receipt, signedContentIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ContentIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signedContentIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Receipt, originatorSignatureValue),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originatorSignatureValue"
		},
};
static ber_tlv_tag_t asn_DEF_Receipt_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Receipt_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 2959 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 1 }, /* signedContentIdentifier at 2961 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 0 }, /* originatorSignatureValue at 2962 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* contentType at 2960 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Receipt_specs_1 = {
	sizeof(struct Receipt),
	offsetof(struct Receipt, _asn_ctx),
	asn_MAP_Receipt_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Receipt = {
	"Receipt",
	"Receipt",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Receipt_tags_1,
	sizeof(asn_DEF_Receipt_tags_1)
		/sizeof(asn_DEF_Receipt_tags_1[0]), /* 1 */
	asn_DEF_Receipt_tags_1,	/* Same as above */
	sizeof(asn_DEF_Receipt_tags_1)
		/sizeof(asn_DEF_Receipt_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Receipt_1,
	4,	/* Elements count */
	&asn_SPC_Receipt_specs_1	/* Additional specs */
};

