/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "RevAnnContent.h"

static asn_TYPE_member_t asn_MBR_RevAnnContent_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RevAnnContent, status),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PKIStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"status"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RevAnnContent, certId),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CertID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RevAnnContent, willBeRevokedAt),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"willBeRevokedAt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RevAnnContent, badSinceDate),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"badSinceDate"
		},
	{ ATF_POINTER, 1, offsetof(struct RevAnnContent, crlDetails),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"crlDetails"
		},
};
static ber_tlv_tag_t asn_DEF_RevAnnContent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RevAnnContent_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* status at 2586 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* certId at 2587 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 }, /* crlDetails at 2590 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 2, 0, 1 }, /* willBeRevokedAt at 2588 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 3, -1, 0 } /* badSinceDate at 2589 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RevAnnContent_specs_1 = {
	sizeof(struct RevAnnContent),
	offsetof(struct RevAnnContent, _asn_ctx),
	asn_MAP_RevAnnContent_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RevAnnContent = {
	"RevAnnContent",
	"RevAnnContent",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RevAnnContent_tags_1,
	sizeof(asn_DEF_RevAnnContent_tags_1)
		/sizeof(asn_DEF_RevAnnContent_tags_1[0]), /* 1 */
	asn_DEF_RevAnnContent_tags_1,	/* Same as above */
	sizeof(asn_DEF_RevAnnContent_tags_1)
		/sizeof(asn_DEF_RevAnnContent_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RevAnnContent_1,
	5,	/* Elements count */
	&asn_SPC_RevAnnContent_specs_1	/* Additional specs */
};

