/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXCMP"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "RevDetails.h"

static asn_TYPE_member_t asn_MBR_RevDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RevDetails, certDetails),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CertTemplate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certDetails"
		},
	{ ATF_POINTER, 3, offsetof(struct RevDetails, revocationReason),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_ReasonFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"revocationReason"
		},
	{ ATF_POINTER, 2, offsetof(struct RevDetails, badSinceDate),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"badSinceDate"
		},
	{ ATF_POINTER, 1, offsetof(struct RevDetails, crlEntryDetails),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"crlEntryDetails"
		},
};
static ber_tlv_tag_t asn_DEF_RevDetails_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RevDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* revocationReason at 2559 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* certDetails at 2555 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 }, /* crlEntryDetails at 2563 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 2, 0, 0 } /* badSinceDate at 2561 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RevDetails_specs_1 = {
	sizeof(struct RevDetails),
	offsetof(struct RevDetails, _asn_ctx),
	asn_MAP_RevDetails_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RevDetails = {
	"RevDetails",
	"RevDetails",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RevDetails_tags_1,
	sizeof(asn_DEF_RevDetails_tags_1)
		/sizeof(asn_DEF_RevDetails_tags_1[0]), /* 1 */
	asn_DEF_RevDetails_tags_1,	/* Same as above */
	sizeof(asn_DEF_RevDetails_tags_1)
		/sizeof(asn_DEF_RevDetails_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RevDetails_1,
	4,	/* Elements count */
	&asn_SPC_RevDetails_specs_1	/* Additional specs */
};

