/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignatureFormats-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "RevocationValues.h"

static asn_TYPE_member_t asn_MBR_crlVals_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CertificateList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_crlVals_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_crlVals_specs_2 = {
	sizeof(struct crlVals),
	offsetof(struct crlVals, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crlVals_2 = {
	"crlVals",
	"crlVals",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_crlVals_tags_2,
	sizeof(asn_DEF_crlVals_tags_2)
		/sizeof(asn_DEF_crlVals_tags_2[0]), /* 2 */
	asn_DEF_crlVals_tags_2,	/* Same as above */
	sizeof(asn_DEF_crlVals_tags_2)
		/sizeof(asn_DEF_crlVals_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_crlVals_2,
	1,	/* Single element */
	&asn_SPC_crlVals_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ocspVals_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BasicOCSPResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_ocspVals_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ocspVals_specs_4 = {
	sizeof(struct ocspVals),
	offsetof(struct ocspVals, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ocspVals_4 = {
	"ocspVals",
	"ocspVals",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ocspVals_tags_4,
	sizeof(asn_DEF_ocspVals_tags_4)
		/sizeof(asn_DEF_ocspVals_tags_4[0]), /* 2 */
	asn_DEF_ocspVals_tags_4,	/* Same as above */
	sizeof(asn_DEF_ocspVals_tags_4)
		/sizeof(asn_DEF_ocspVals_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ocspVals_4,
	1,	/* Single element */
	&asn_SPC_ocspVals_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RevocationValues_1[] = {
	{ ATF_POINTER, 2, offsetof(struct RevocationValues, crlVals),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_crlVals_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"crlVals"
		},
	{ ATF_POINTER, 1, offsetof(struct RevocationValues, ocspVals),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ocspVals_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ocspVals"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RevocationValues, otherRevVals),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OtherRevVals,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otherRevVals"
		},
};
static ber_tlv_tag_t asn_DEF_RevocationValues_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RevocationValues_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crlVals at 302 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ocspVals at 303 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* otherRevVals at 305 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RevocationValues_specs_1 = {
	sizeof(struct RevocationValues),
	offsetof(struct RevocationValues, _asn_ctx),
	asn_MAP_RevocationValues_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RevocationValues = {
	"RevocationValues",
	"RevocationValues",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RevocationValues_tags_1,
	sizeof(asn_DEF_RevocationValues_tags_1)
		/sizeof(asn_DEF_RevocationValues_tags_1[0]), /* 1 */
	asn_DEF_RevocationValues_tags_1,	/* Same as above */
	sizeof(asn_DEF_RevocationValues_tags_1)
		/sizeof(asn_DEF_RevocationValues_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RevocationValues_1,
	3,	/* Elements count */
	&asn_SPC_RevocationValues_specs_1	/* Additional specs */
};

