/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "lpa.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "SignPolicyInfo.h"

static asn_TYPE_member_t asn_MBR_SignPolicyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignPolicyInfo, signPolicyIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SignaturePolicyId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signPolicyIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignPolicyInfo, dateOfIssue),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dateOfIssue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignPolicyInfo, policyIssuerName),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PolicyIssuerName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policyIssuerName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignPolicyInfo, fieldOfApplication),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_FieldOfApplication,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fieldOfApplication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignPolicyInfo, signatureValidationPolicy),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SignatureValidationPolicy,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signatureValidationPolicy"
		},
	{ ATF_POINTER, 1, offsetof(struct SignPolicyInfo, signPolExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SignPolExtensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signPolExtensions"
		},
};
static ber_tlv_tag_t asn_DEF_SignPolicyInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SignPolicyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, 0, 0 }, /* utf8String at 558 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 3 }, /* signPolicyIdentifier at 985 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 2 }, /* policyIssuerName at 987 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -2, 1 }, /* signatureValidationPolicy at 989 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -3, 0 }, /* signPolExtensions at 991 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 3, 0, 0 }, /* printableString at 556 */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 3, 0, 0 }, /* teletexString at 555 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 1, 0, 0 }, /* dateOfIssue at 986 */
    { (ASN_TAG_CLASS_UNIVERSAL | (28 << 2)), 3, 0, 0 }, /* universalString at 557 */
    { (ASN_TAG_CLASS_UNIVERSAL | (30 << 2)), 3, 0, 0 } /* bmpString at 559 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignPolicyInfo_specs_1 = {
	sizeof(struct SignPolicyInfo),
	offsetof(struct SignPolicyInfo, _asn_ctx),
	asn_MAP_SignPolicyInfo_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SignPolicyInfo = {
	"SignPolicyInfo",
	"SignPolicyInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SignPolicyInfo_tags_1,
	sizeof(asn_DEF_SignPolicyInfo_tags_1)
		/sizeof(asn_DEF_SignPolicyInfo_tags_1[0]), /* 1 */
	asn_DEF_SignPolicyInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignPolicyInfo_tags_1)
		/sizeof(asn_DEF_SignPolicyInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SignPolicyInfo_1,
	6,	/* Elements count */
	&asn_SPC_SignPolicyInfo_specs_1	/* Additional specs */
};

