/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "lpa2.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "TBSRequest.h"

static int asn_DFL_2_set_0(int set_value, void **sptr) {
	OCSP_Version_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static asn_TYPE_member_t asn_MBR_requestList_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_requestList_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_requestList_specs_4 = {
	sizeof(struct requestList),
	offsetof(struct requestList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requestList_4 = {
	"requestList",
	"requestList",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_requestList_tags_4,
	sizeof(asn_DEF_requestList_tags_4)
		/sizeof(asn_DEF_requestList_tags_4[0]), /* 1 */
	asn_DEF_requestList_tags_4,	/* Same as above */
	sizeof(asn_DEF_requestList_tags_4)
		/sizeof(asn_DEF_requestList_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_requestList_4,
	1,	/* Single element */
	&asn_SPC_requestList_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TBSRequest_1[] = {
	{ ATF_NOFLAGS, 2, offsetof(struct TBSRequest, version),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCSP_Version,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_0,	/* DEFAULT 0 */
		"version"
		},
	{ ATF_POINTER, 1, offsetof(struct TBSRequest, requestorName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestorName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBSRequest, requestList),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_requestList_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestList"
		},
	{ ATF_POINTER, 1, offsetof(struct TBSRequest, requestExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestExtensions"
		},
};
static ber_tlv_tag_t asn_DEF_TBSRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TBSRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* requestList at 3159 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* version at 3157 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* requestorName at 3158 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 } /* requestExtensions at 3160 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TBSRequest_specs_1 = {
	sizeof(struct TBSRequest),
	offsetof(struct TBSRequest, _asn_ctx),
	asn_MAP_TBSRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TBSRequest = {
	"TBSRequest",
	"TBSRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TBSRequest_tags_1,
	sizeof(asn_DEF_TBSRequest_tags_1)
		/sizeof(asn_DEF_TBSRequest_tags_1[0]), /* 1 */
	asn_DEF_TBSRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_TBSRequest_tags_1)
		/sizeof(asn_DEF_TBSRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TBSRequest_1,
	4,	/* Elements count */
	&asn_SPC_TBSRequest_specs_1	/* Additional specs */
};

